package ru.tzfviewer;

import android.app.Dialog;
import android.content.Context;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.ColorDrawable;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.view.WindowManager;
import android.view.inputmethod.InputMethodManager;
import android.text.InputType;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import java.util.List;

final class InstrumentDialog {
    interface TextAccepted { void accept(String value); }
    interface NumberAccepted { void accept(double value); }
    interface CredentialsAccepted { void accept(String host,String user,String password); }
    interface MultiAccepted { void accept(boolean[] selected); }
    private InstrumentDialog(){}

    static void input(Context context,String eyebrow,String title,String message,String label,String value,String hint,String primary,TextAccepted accepted){
        Dialog dialog=create(context);LinearLayout card=card(context,eyebrow,title,message);TextView fieldLabel=label(context,label);card.addView(fieldLabel);EditText input=new EditText(context);input.setSingleLine(true);input.setText(value);input.setSelectAllOnFocus(true);input.setHint(hint);input.setTextColor(context.getColor(R.color.text_primary));input.setHintTextColor(context.getColor(R.color.text_secondary));input.setTextSize(16);input.setPadding(dp(context,15),0,dp(context,15),0);input.setBackgroundResource(R.drawable.bg_instrument_input);card.addView(input,new LinearLayout.LayoutParams(-1,dp(context,58)));TextView helper=InstrumentMenu.text(context,"Можно изменить позже",11,R.color.text_secondary);helper.setPadding(0,dp(context,7),0,0);card.addView(helper);LinearLayout actions=actions(context);Button cancel=button(context,"Отмена",false,false),ok=button(context,primary,true,false);actions.addView(cancel);actions.addView(ok);card.addView(actions);dialog.setContentView(card);cancel.setOnClickListener(v->dialog.dismiss());ok.setOnClickListener(v->{String text=input.getText().toString().trim();if(text.isEmpty()){helper.setText("Введите название");helper.setTextColor(context.getColor(R.color.danger));input.requestFocus();return;}dialog.dismiss();accepted.accept(text);});show(dialog,context);input.requestFocus();input.postDelayed(()->{InputMethodManager keyboard=(InputMethodManager)context.getSystemService(Context.INPUT_METHOD_SERVICE);if(keyboard!=null)keyboard.showSoftInput(input,InputMethodManager.SHOW_IMPLICIT);},180);
    }

    static void number(Context context,String eyebrow,String title,String message,String label,String hint,boolean integer,double maximum,NumberAccepted accepted){Dialog dialog=create(context);LinearLayout card=card(context,eyebrow,title,message);card.addView(label(context,label));EditText input=input(context,"",hint,integer?InputType.TYPE_CLASS_NUMBER:InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL,false);card.addView(input,new LinearLayout.LayoutParams(-1,dp(context,58)));TextView helper=InstrumentMenu.text(context,maximum>0?"Допустимо: больше 0 и не больше "+maximum:"Введите значение больше нуля",11,R.color.text_secondary);helper.setPadding(0,dp(context,7),0,0);card.addView(helper);LinearLayout actions=actions(context);Button cancel=button(context,"Отмена",false,false),ok=button(context,"Продолжить",true,false);actions.addView(cancel);actions.addView(ok);card.addView(actions);dialog.setContentView(card);cancel.setOnClickListener(v->dialog.dismiss());ok.setOnClickListener(v->{try{double value=Double.parseDouble(input.getText().toString().trim().replace(',','.').replace(" ",""));if(!Double.isFinite(value)||value<=0||(maximum>0&&value>maximum))throw new NumberFormatException();dialog.dismiss();accepted.accept(value);}catch(Exception error){helper.setText("Введите корректное число");helper.setTextColor(context.getColor(R.color.danger));input.requestFocus();}});show(dialog,context);input.requestFocus();}

    static void credentials(Context context,String hostValue,String userValue,String passwordValue,CredentialsAccepted accepted){Dialog dialog=create(context);LinearLayout card=card(context,"Trimble X7","Подключить сканер","Телефон должен быть подключён к Wi‑Fi сети X7.");card.addView(label(context,"IP-адрес"));EditText host=input(context,hostValue,"192.168.43.1",InputType.TYPE_CLASS_PHONE,false);card.addView(host,new LinearLayout.LayoutParams(-1,dp(context,54)));TextView userLabel=label(context,"FTP-логин");userLabel.setPadding(0,dp(context,14),0,dp(context,8));card.addView(userLabel);EditText user=input(context,userValue,"media",InputType.TYPE_CLASS_TEXT,false);card.addView(user,new LinearLayout.LayoutParams(-1,dp(context,54)));TextView passwordLabel=label(context,"FTP-пароль");passwordLabel.setPadding(0,dp(context,14),0,dp(context,8));card.addView(passwordLabel);EditText password=input(context,passwordValue,"media",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD,true);card.addView(password,new LinearLayout.LayoutParams(-1,dp(context,54)));TextView helper=InstrumentMenu.text(context,"Данные сохраняются только на устройстве",11,R.color.text_secondary);helper.setPadding(0,dp(context,8),0,0);card.addView(helper);LinearLayout actions=actions(context);Button cancel=button(context,"Отмена",false,false),ok=button(context,"Подключить",true,false);actions.addView(cancel);actions.addView(ok);card.addView(actions);dialog.setContentView(card);cancel.setOnClickListener(v->dialog.dismiss());ok.setOnClickListener(v->{String h=host.getText().toString().trim(),u=user.getText().toString().trim(),p=password.getText().toString();if(h.isEmpty()||u.isEmpty()||p.isEmpty()){helper.setText("Заполните все поля");helper.setTextColor(context.getColor(R.color.danger));return;}dialog.dismiss();accepted.accept(h,u,p);});show(dialog,context);host.requestFocus();}

    static void multiChoice(Context context,String eyebrow,String title,String message,String[] labels,String primary,MultiAccepted accepted,Runnable all,Runnable cancelled){Dialog dialog=create(context);LinearLayout card=card(context,eyebrow,title,message);MaxHeightScroll scroll=new MaxHeightScroll(context,390);LinearLayout list=new LinearLayout(context);list.setOrientation(LinearLayout.VERTICAL);boolean[] selected=new boolean[labels.length];for(int i=0;i<labels.length;i++){int index=i;InstrumentMenu.Action choice=InstrumentMenu.Action.item("□",labels[i],"Нажмите, чтобы выбрать",null);View row=InstrumentMenu.row(context,choice,()->{});TextView mark=InstrumentMenu.text(context,"",11,R.color.cyan);mark.setTypeface(Typeface.MONOSPACE);mark.setPadding(dp(context,7),dp(context,4),dp(context,7),dp(context,4));((LinearLayout)row).addView(mark);row.setOnClickListener(v->{selected[index]=!selected[index];row.setBackgroundResource(selected[index]?R.drawable.bg_instrument_row_active:R.drawable.bg_instrument_row);mark.setText(selected[index]?"ВЫБРАН":"");});list.addView(row);}scroll.addView(list);card.addView(scroll,new LinearLayout.LayoutParams(-1,-2));LinearLayout actions=actions(context);Button allButton=button(context,"Добавить все",false,false),ok=button(context,primary,true,false);actions.addView(allButton);actions.addView(ok);card.addView(actions);dialog.setContentView(card);allButton.setOnClickListener(v->{dialog.dismiss();all.run();});ok.setOnClickListener(v->{dialog.dismiss();accepted.accept(selected.clone());});dialog.setOnCancelListener(d->{if(cancelled!=null)cancelled.run();});show(dialog,context);}

    static void actions(Context context,String eyebrow,String title,String message,List<InstrumentMenu.Action> choices,Runnable cancelled){Dialog dialog=create(context);LinearLayout card=card(context,eyebrow,title,message);MaxHeightScroll scroll=new MaxHeightScroll(context,420);LinearLayout list=new LinearLayout(context);list.setOrientation(LinearLayout.VERTICAL);for(InstrumentMenu.Action choice:choices){if(choice.dividerBefore)list.addView(InstrumentMenu.divider(context));list.addView(InstrumentMenu.row(context,choice,()->{dialog.dismiss();if(choice.run!=null)choice.run.run();}));}scroll.addView(list);card.addView(scroll,new LinearLayout.LayoutParams(-1,-2));dialog.setContentView(card);dialog.setOnCancelListener(d->{if(cancelled!=null)cancelled.run();});show(dialog,context);}

    static void confirm(Context context,String eyebrow,String title,String message,String primary,boolean danger,Runnable accepted){Dialog dialog=create(context);LinearLayout card=card(context,eyebrow,title,message);LinearLayout actions=actions(context);Button cancel=button(context,"Отмена",false,false),ok=button(context,primary,!danger,danger);actions.addView(cancel);actions.addView(ok);card.addView(actions);dialog.setContentView(card);cancel.setOnClickListener(v->dialog.dismiss());ok.setOnClickListener(v->{dialog.dismiss();accepted.run();});show(dialog,context);}

    private static Dialog create(Context context){Dialog dialog=new Dialog(context);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);return dialog;}
    private static LinearLayout card(Context context,String eyebrow,String title,String message){LinearLayout card=new LinearLayout(context);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(context,24),dp(context,22),dp(context,24),dp(context,22));card.setBackgroundResource(R.drawable.bg_instrument_card);View accent=new View(context);accent.setBackgroundColor(context.getColor(R.color.cyan));LinearLayout.LayoutParams accentParams=new LinearLayout.LayoutParams(dp(context,44),dp(context,3));accentParams.setMargins(0,0,0,dp(context,18));card.addView(accent,accentParams);TextView over=InstrumentMenu.text(context,eyebrow.toUpperCase(),11,R.color.text_secondary);over.setTypeface(Typeface.MONOSPACE);over.setLetterSpacing(.14f);card.addView(over);TextView heading=InstrumentMenu.text(context,title,25,R.color.text_primary);heading.setTypeface(Typeface.DEFAULT,Typeface.BOLD);heading.setPadding(0,dp(context,7),0,message==null||message.isEmpty()?dp(context,17):dp(context,6));card.addView(heading);if(message!=null&&!message.isEmpty()){TextView body=InstrumentMenu.text(context,message,13,R.color.text_secondary);body.setLineSpacing(0,1.15f);body.setPadding(0,0,0,dp(context,20));card.addView(body);}return card;}
    private static TextView label(Context context,String value){TextView label=InstrumentMenu.text(context,value.toUpperCase(),11,R.color.text_secondary);label.setTypeface(Typeface.MONOSPACE);label.setLetterSpacing(.12f);label.setPadding(0,0,0,dp(context,8));return label;}
    private static EditText input(Context context,String value,String hint,int inputType,boolean password){EditText input=new EditText(context);input.setSingleLine(true);input.setText(value);input.setHint(hint);input.setInputType(inputType);input.setTextColor(context.getColor(R.color.text_primary));input.setHintTextColor(context.getColor(R.color.text_secondary));input.setTextSize(16);input.setPadding(dp(context,15),0,dp(context,15),0);input.setBackgroundResource(R.drawable.bg_instrument_input);if(password)input.setTypeface(Typeface.DEFAULT);return input;}
    private static LinearLayout actions(Context context){LinearLayout actions=new LinearLayout(context);actions.setGravity(Gravity.END);actions.setPadding(0,dp(context,23),0,0);return actions;}
    private static Button button(Context context,String text,boolean primary,boolean danger){Button button=new Button(context);button.setAllCaps(false);button.setText(text);button.setTextSize(13);button.setTypeface(Typeface.DEFAULT,Typeface.BOLD);button.setTextColor(context.getColor(primary?R.color.ink:R.color.text_primary));button.setBackgroundResource(danger?R.drawable.bg_instrument_danger:primary?R.drawable.bg_instrument_primary:R.drawable.bg_instrument_secondary);LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,dp(context,46));params.setMargins(dp(context,10),0,0,0);button.setLayoutParams(params);button.setMinWidth(dp(context,92));button.setPadding(dp(context,17),0,dp(context,17),0);return button;}
    private static void show(Dialog dialog,Context context){Window window=dialog.getWindow();if(window!=null){window.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));window.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);window.setDimAmount(.74f);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}dialog.show();window=dialog.getWindow();if(window!=null){int width=Math.min(dp(context,440),context.getResources().getDisplayMetrics().widthPixels-dp(context,32));window.setLayout(width,ViewGroup.LayoutParams.WRAP_CONTENT);window.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));}}
    private static int dp(Context context,int value){return InstrumentMenu.dp(context,value);}
    private static final class MaxHeightScroll extends ScrollView {private final int max;MaxHeightScroll(Context context,int maxDp){super(context);max=dp(context,maxDp);setFillViewport(false);setVerticalScrollBarEnabled(false);}@Override protected void onMeasure(int width,int height){super.onMeasure(width,MeasureSpec.makeMeasureSpec(max,MeasureSpec.AT_MOST));}}
}
