package ru.tzfviewer;
import android.content.Context; import android.graphics.Color; import android.graphics.Rect; import android.graphics.Typeface; import android.graphics.drawable.ColorDrawable; import android.view.Gravity; import android.view.View; import android.view.ViewGroup; import android.widget.LinearLayout; import android.widget.PopupWindow; import android.widget.TextView; import java.util.List;
final class InstrumentMenu {
 static final class Action { final String icon,title,subtitle,trailing; final boolean selected,danger,dividerBefore; final Runnable run; Action(String i,String t,String s,String r,boolean a,boolean d,boolean b,Runnable x){icon=i;title=t;subtitle=s;trailing=r;selected=a;danger=d;dividerBefore=b;run=x;} static Action item(String i,String t,String s,Runnable r){return new Action(i,t,s,"",false,false,"Сетка".equals(t),r);} Action state(String v,boolean a){return new Action(icon,title,subtitle,v,a,danger,dividerBefore,run);} Action danger(){return new Action(icon,title,subtitle,trailing,selected,true,dividerBefore,run);} Action divided(){return new Action(icon,title,subtitle,trailing,selected,danger,true,run);} }
 private InstrumentMenu(){}
 static void show(View anchor,String eyebrow,List<Action> actions){Context c=anchor.getContext();LinearLayout card=card(c,eyebrow);PopupWindow p=new PopupWindow(card,dp(c,280),ViewGroup.LayoutParams.WRAP_CONTENT,true);p.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));p.setOutsideTouchable(true);p.setElevation(dp(c,18));for(Action a:actions){if(a.dividerBefore)card.addView(divider(c));card.addView(row(c,a,()->{p.dismiss();if(a.run!=null)a.run.run();}));}card.measure(View.MeasureSpec.makeMeasureSpec(dp(c,280),View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(0,View.MeasureSpec.UNSPECIFIED));int[] pt=new int[2];anchor.getLocationOnScreen(pt);Rect f=new Rect();anchor.getWindowVisibleDisplayFrame(f);int w=card.getMeasuredWidth(),h=card.getMeasuredHeight(),g=dp(c,8),x=pt[0]+anchor.getWidth()+g;if(x+w>f.right-g)x=pt[0]-w-g;x=Math.max(f.left+g,x);int y=Math.max(f.top+g,Math.min(pt[1]-h/2+anchor.getHeight()/2,f.bottom-h-g));p.showAtLocation(anchor.getRootView(),Gravity.NO_GRAVITY,x,y);}
 static LinearLayout card(Context c,String e){LinearLayout v=new LinearLayout(c);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(dp(c,10),dp(c,10),dp(c,10),dp(c,10));v.setBackgroundResource(R.drawable.bg_instrument_card);TextView l=text(c,e.toUpperCase(),10,R.color.text_secondary);l.setTypeface(Typeface.MONOSPACE);l.setLetterSpacing(.14f);l.setPadding(dp(c,7),dp(c,3),dp(c,7),dp(c,7));v.addView(l);return v;}
 static View row(Context c,Action a,Runnable click){LinearLayout r=new LinearLayout(c);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(c,7),dp(c,5),dp(c,7),dp(c,5));r.setMinimumHeight(dp(c,48));r.setBackgroundResource(a.selected?R.drawable.bg_instrument_row_active:R.drawable.bg_instrument_row);TextView icon=text(c,a.icon,11,a.danger?R.color.danger:a.selected?R.color.cyan:R.color.text_primary);icon.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);icon.setGravity(Gravity.CENTER);icon.setBackgroundResource(R.drawable.bg_instrument_icon);r.addView(icon,new LinearLayout.LayoutParams(dp(c,34),dp(c,34)));LinearLayout words=new LinearLayout(c);words.setOrientation(LinearLayout.VERTICAL);words.setPadding(dp(c,8),0,dp(c,4),0);TextView title=text(c,a.title,14,a.danger?R.color.danger:R.color.text_primary);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);words.addView(title);if(a.subtitle!=null&&!a.subtitle.isEmpty()){TextView sub=text(c,a.subtitle,10,R.color.text_secondary);sub.setPadding(0,dp(c,1),0,0);words.addView(sub);}r.addView(words,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));if(a.trailing!=null&&!a.trailing.isEmpty()){TextView t=text(c,a.trailing,9,a.danger?R.color.danger:R.color.cyan);t.setTypeface(Typeface.MONOSPACE);t.setGravity(Gravity.CENTER);t.setPadding(dp(c,6),dp(c,3),dp(c,6),dp(c,3));t.setBackgroundResource(R.drawable.bg_instrument_pill);r.addView(t);}r.setContentDescription(a.title);r.setOnClickListener(v->click.run());return r;}
 static View divider(Context c){View v=new View(c);v.setBackgroundColor(Color.rgb(41,68,83));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(c,1));p.setMargins(dp(c,7),dp(c,5),dp(c,7),dp(c,5));v.setLayoutParams(p);return v;} static TextView text(Context c,String s,float z,int color){TextView v=new TextView(c);v.setText(s);v.setTextSize(z);v.setTextColor(c.getColor(color));return v;} static int dp(Context c,int n){return Math.round(n*c.getResources().getDisplayMetrics().density);}
}
