package ru.tzfviewer;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ClipData;
import android.content.Intent;
import android.net.Uri;
import androidx.documentfile.provider.DocumentFile;
import android.os.Bundle;
import android.provider.OpenableColumns;
import android.view.View;
import android.view.Gravity;
import android.text.InputType;
import android.widget.PopupMenu;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.SeekBar;
import android.widget.TextView;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.BufferedWriter;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Random;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicInteger;

public final class MainActivity extends Activity {
    static final String EXTRA_PROJECT_ID = "project_id";
    static final String EXTRA_X7_PREVIEW_PATH = "x7_preview_path";
    private static final int PICK_TZF = 103;
    private static final int PREVIEW_X7 = 104;
    private static final int CREATE_ASC = 106;
    private static final int[] POINT_BUDGETS={-1,150_000,1_000_000,10_000_000,-2};
    private static final int[] POINT_SIZES={1,2,3,5};
    private static final int[] SCAN_COLORS={0xff38c9e8,0xffffb44a,0xff8ee06f,0xffd58cff,0xffff718a,0xffffed61,0xff5f8cff,0xff63e6be};
    private static final double DEFAULT_RMS_LIMIT=3.0,DEFAULT_P95_LIMIT=8.0;
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private final AtomicInteger registrationGeneration=new AtomicInteger();
    private final ConcurrentHashMap<String,AtomicInteger> sceneGenerations=new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String,NativePreviewSession> sessions=new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String,File> localFiles=new ConcurrentHashMap<>();
    private final Random random=new Random();
    private final AutoPointBudget autoPointBudget=new AutoPointBudget();
    private ProjectStore store;
    private ProjectModel project;
    private PointCloudView cloud;
    private ScanTreePanel tree;
    private TextView status,referenceLabel,movingLabel,transformSummary;
    private Button cancelButton,applyCandidateButton,rejectCandidateButton,pointSizeButton,budgetButton,stitchMenuButton,scanX7Button,cancelX7Button,manipulatorStitchButton,exitManipulatorButton,orbitModeButton;
    private ProgressBar registrationProgress,x7Progress;
    private View scanPanel,settingsPanel;
    private View pairCard;
    private View clipPanel;
    private SeekBar clipLowerBar,clipUpperBar;
    private boolean updatingClipUi;
    private int budgetIndex,pointSizeIndex;
    private boolean stitchingActionsEnabled=true,manipulatorMode;
    private float[] candidateWorld,candidateOriginalWorld;
    private List<ProjectModel.Scan> candidateGraphScans;
    private float[] candidateGraphWorld;
    private boolean x7Running;
    private boolean expandedLayout;
    private boolean clipEnabled,clipLocked;
    private boolean previewMode,previewInFlight;
    private File previewFile;
    private volatile TrimbleX7Client activeX7Client;
    private volatile int activeX7TaskId=-1;
    private volatile boolean x7CancelRequested;

    @Override public void onCreate(Bundle state){
        super.onCreate(state);
        store=new ProjectStore(getFilesDir());String previewPath=getIntent().getStringExtra(EXTRA_X7_PREVIEW_PATH);previewMode=previewPath!=null;if(previewMode){previewFile=new File(previewPath);if(!previewFile.isFile()){finish();return;}project=ProjectModel.create("Предпросмотр X7",System.currentTimeMillis());project.pointBudget=10_000_000;ProjectModel.Scan scan=new ProjectModel.Scan(UUID.randomUUID().toString(),previewFile.getName());scan.uri=Uri.fromFile(previewFile).toString();project.root.add(scan);}else{String id=getIntent().getStringExtra(EXTRA_PROJECT_ID);if(id==null){finish();return;}try{project=store.load(id);}catch(Exception error){finish();return;}}
        setContentView(R.layout.activity_main);
        expandedLayout=getResources().getBoolean(R.bool.expanded_layout);
        cloud=new PointCloudView(this);
        cloud.setPerformanceListener(this::sampleAutoBudget);
        cloud.setSceneErrorListener(this::handleSceneGpuError);
        cloud.setContextLossListener(this::reloadAll);
        cloud.setAutoPerformanceMode(project.pointBudget==-1);
        ((FrameLayout)findViewById(R.id.viewportContainer)).addView(cloud,0,new FrameLayout.LayoutParams(-1,-1));
        bindViews();bindCamera();bindTools();configureAdaptiveUi();bindTree();
        cloud.setTransformListener(this::applyMovingWorldTransform);
        cloud.setTransformCommitListener(this::changed);
        cloud.setPointSize(project.pointSize);cloud.setGridVisible(project.gridVisible);cloud.restoreOrientation(project.cameraYaw,project.cameraPitch);if(project.orthographic)cloud.toggleProjection();
        updateRoleUi();syncScene();restoreProjectScans();sizeOverlays();
    }

    private void bindViews(){
        ((TextView)findViewById(R.id.projectTitle)).setText(project.name);
        status=findViewById(R.id.status);referenceLabel=findViewById(R.id.referenceLabel);movingLabel=findViewById(R.id.movingLabel);transformSummary=findViewById(R.id.transformSummary);
        cancelButton=findViewById(R.id.cancelRegistration);applyCandidateButton=findViewById(R.id.applyCandidate);rejectCandidateButton=findViewById(R.id.rejectCandidate);registrationProgress=findViewById(R.id.registrationProgress);stitchMenuButton=findViewById(R.id.moreTools);manipulatorStitchButton=findViewById(R.id.manipulatorStitch);exitManipulatorButton=findViewById(R.id.exitManipulator);
        scanPanel=findViewById(R.id.scanPanel);settingsPanel=findViewById(R.id.settingsPanel);pairCard=findViewById(R.id.pairCard);tree=findViewById(R.id.scanTree);pointSizeButton=findViewById(R.id.pointSize);budgetButton=findViewById(R.id.pointBudget);scanX7Button=findViewById(R.id.scanX7);x7Progress=findViewById(R.id.x7Progress);cancelX7Button=findViewById(R.id.cancelX7);orbitModeButton=findViewById(R.id.orbitMode);
    }

    private void bindCamera(){
        OrientationCubeView cube=findViewById(R.id.orientation);cube.setListener(new OrientationCubeView.Listener(){public void onPreset(float yaw,float pitch){cloud.setPreset(yaw,pitch);}public void onRotate(float dy,float dp){cloud.rotateCamera(dy,dp);}});
        cloud.setOrientationListener((yaw,pitch)->{cube.setOrientation(yaw,pitch);if(!manipulatorMode){project.cameraYaw=yaw;project.cameraPitch=pitch;project.touch(System.currentTimeMillis());}});
        orbitModeButton.setOnClickListener(v->setOrbitMode(!cloud.orbitEnabled()));
        setOrbitMode(false);
    }

    private void setOrbitMode(boolean enabled){cloud.setOrbitEnabled(enabled);boolean active=cloud.orbitEnabled();orbitModeButton.setSelected(active);orbitModeButton.setBackgroundColor(getColor(active?R.color.cyan:R.color.panel_raised));orbitModeButton.setTextColor(getColor(active?R.color.ink:R.color.text_primary));orbitModeButton.setContentDescription(getString(active?R.string.orbit_mode_on:R.string.orbit_mode_off));}

    private void bindTools(){
        findViewById(R.id.compactOpen).setOnClickListener(v->selectTzf());
        findViewById(R.id.saveProject).setOnClickListener(v->persistProjectFilesSafely());
        findViewById(R.id.exportAsc).setOnClickListener(v->chooseAscDestination());
        scanX7Button.setOnClickListener(v->connectX7(new TrimbleX7Client("192.168.43.1","media","media")));if(previewMode){scanX7Button.setVisibility(View.GONE);findViewById(R.id.compactOpen).setVisibility(View.GONE);}
        cancelX7Button.setOnClickListener(v->cancelX7Scan());
        findViewById(R.id.backToProjects).setOnClickListener(v->navigateToProjects());
        findViewById(R.id.compactFit).setOnClickListener(v->{if(readyScans().isEmpty())status.setText("Нет видимых готовых облаков");else cloud.fitView();});
        findViewById(R.id.scans).setOnClickListener(v->togglePanel(scanPanel,settingsPanel));findViewById(R.id.closeScans).setOnClickListener(v->scanPanel.setVisibility(View.GONE));
        stitchMenuButton.setOnClickListener(this::showToolsMenu);findViewById(R.id.closeSettings).setOnClickListener(v->settingsPanel.setVisibility(View.GONE));
        findViewById(R.id.pairDetails).setOnClickListener(v->togglePanel(settingsPanel,scanPanel));
        findViewById(R.id.compactProjection).setOnClickListener(v->{if(manipulatorMode){status.setText("В манипуляторе зафиксирован вид сверху");return;}project.orthographic=!project.orthographic;cloud.toggleProjection();changed();});
        findViewById(R.id.grid).setOnClickListener(v->{project.gridVisible=!project.gridVisible;cloud.setGridVisible(project.gridVisible);changed();});
        bindClipping();
        for(int i=0;i<POINT_BUDGETS.length;i++)if(POINT_BUDGETS[i]==project.pointBudget)budgetIndex=i;for(int i=0;i<POINT_SIZES.length;i++)if(POINT_SIZES[i]==project.pointSize)pointSizeIndex=i;
        updatePointControlLabels();
        pointSizeButton.setOnClickListener(v->{pointSizeIndex=(pointSizeIndex+1)%POINT_SIZES.length;project.pointSize=POINT_SIZES[pointSizeIndex];cloud.setPointSize(project.pointSize);updatePointControlLabels();changed();});
        budgetButton.setOnClickListener(v->{budgetIndex=(budgetIndex+1)%POINT_BUDGETS.length;project.pointBudget=POINT_BUDGETS[budgetIndex];updatePointControlLabels();cloud.setAutoPerformanceMode(project.pointBudget==-1);reloadAll();changed();});
        Button measure=findViewById(R.id.measure);measure.setOnClickListener(v->{measure.setSelected(!measure.isSelected());cloud.setMeasureMode(measure.isSelected(),(length,dz)->status.setText(String.format(Locale.US,"Расстояние %.3f · ΔZ %.3f",length,dz)));});
        cancelButton.setOnClickListener(v->cancelRegistration());applyCandidateButton.setOnClickListener(v->applyRegistrationCandidate());rejectCandidateButton.setOnClickListener(v->rejectRegistrationCandidate());
        manipulatorStitchButton.setOnClickListener(v->startRegistration());exitManipulatorButton.setOnClickListener(v->exitManipulatorMode(true));
        findViewById(R.id.resetTransform).setOnClickListener(v->resetMoving());findViewById(R.id.saveTransform).setOnClickListener(v->saveMovingSnapshot());findViewById(R.id.restoreTransform).setOnClickListener(v->restoreMovingSnapshot());
        setRegistrationRunning(false);
    }

    private void bindClipping(){
        clipPanel=findViewById(R.id.zClipPanel);clipLowerBar=findViewById(R.id.zClipLower);clipUpperBar=findViewById(R.id.zClipUpper);cloud.setClipListener(this::onClipChanged);
        findViewById(R.id.section).setOnClickListener(v->{if(clipEnabled){disableClipping();return;}if(readyScans().isEmpty()){status.setText("Сначала дождитесь загрузки скана");return;}clipEnabled=true;clipLocked=false;project.clipEnabled=true;project.clipLocked=false;cloud.setClipControlsVisible(true);cloud.enableDefaultClip(true);clipPanel.setVisibility(View.VISIBLE);});
        SeekBar.OnSeekBarChangeListener listener=new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar bar,int value,boolean user){if(!user||updatingClipUi||clipLocked)return;int lo=Math.min(clipLowerBar.getProgress(),clipUpperBar.getProgress()-1),hi=Math.max(clipUpperBar.getProgress(),lo+1);cloud.setZClipFractions(lo/100f,hi/100f);}public void onStartTrackingTouch(SeekBar bar){}public void onStopTrackingTouch(SeekBar bar){if(!updatingClipUi&&clipEnabled&&!clipLocked)cloud.commitClipBounds();}};clipLowerBar.setOnSeekBarChangeListener(listener);clipUpperBar.setOnSeekBarChangeListener(listener);
        findViewById(R.id.lockClip).setOnClickListener(v->{if(!clipEnabled)return;clipLocked=true;project.clipLocked=true;cloud.setClipControlsVisible(false);clipPanel.setVisibility(View.GONE);changed();status.setText("Сечение зафиксировано");});
        findViewById(R.id.resetClip).setOnClickListener(v->disableClipping());
        clipEnabled=project.clipEnabled&&ClipBoxMath.valid(project.clipBounds);clipLocked=clipEnabled&&project.clipLocked;if(clipEnabled){cloud.setClipBounds(Arrays.copyOfRange(project.clipBounds,0,3),Arrays.copyOfRange(project.clipBounds,3,6),true);cloud.setClipControlsVisible(!clipLocked);clipPanel.setVisibility(clipLocked?View.GONE:View.VISIBLE);}else{project.clipEnabled=false;project.clipLocked=false;}
    }

    private void disableClipping(){clipEnabled=false;clipLocked=false;project.clipEnabled=false;project.clipLocked=false;Arrays.fill(project.clipBounds,0);updatingClipUi=true;clipLowerBar.setProgress(0);clipUpperBar.setProgress(100);updatingClipUi=false;cloud.enableDefaultClip(false);cloud.setClipControlsVisible(true);clipPanel.setVisibility(View.GONE);changed();}
    private void onClipChanged(float[] bounds,float[] frame,boolean commit){if(!clipEnabled)return;if(!ClipBoxMath.valid(bounds)){clipEnabled=false;project.clipEnabled=false;clipPanel.setVisibility(View.GONE);status.setText("Сечение: нет готовых точек");return;}System.arraycopy(bounds,0,project.clipBounds,0,6);project.clipEnabled=true;project.clipLocked=clipLocked;if(ClipBoxMath.valid(frame)){float range=Math.max(.001f,frame[5]-frame[2]);int lower=Math.max(0,Math.min(100,Math.round((bounds[2]-frame[2])/range*100))),upper=Math.max(0,Math.min(100,Math.round((bounds[5]-frame[2])/range*100)));updatingClipUi=true;clipLowerBar.setProgress(Math.min(lower,upper-1));clipUpperBar.setProgress(Math.max(upper,lower+1));updatingClipUi=false;}if(commit)changed();}

    private void bindTree(){tree.bind(project,new ScanTreePanel.Listener(){public void changed(){rejectRegistrationCandidate();MainActivity.this.changed();syncScene();updateRoleUi();}public void visibilityChanged(ProjectModel.Node node){rejectRegistrationCandidate();syncScene();}public void rolesChanged(){exitManipulatorMode(false);rejectRegistrationCandidate();updateRoleUi();syncScene();}});}
    private void configureAdaptiveUi(){findViewById(R.id.saveProject).setVisibility(View.GONE);findViewById(R.id.compactFit).setVisibility(View.GONE);if(!expandedLayout){int[] secondary={R.id.exportAsc,R.id.measure,R.id.compactProjection,R.id.grid};for(int id:secondary)findViewById(id).setVisibility(View.GONE);pointSizeButton.setVisibility(View.VISIBLE);budgetButton.setVisibility(View.VISIBLE);stitchMenuButton.setText("⋯");}else{View rail=findViewById(R.id.compactTools);FrameLayout.LayoutParams railParams=(FrameLayout.LayoutParams)rail.getLayoutParams();railParams.width=dp(152);rail.setLayoutParams(railParams);int[] ids={R.id.scanX7,R.id.compactOpen,R.id.exportAsc,R.id.scans,R.id.measure,R.id.compactProjection,R.id.grid,R.id.section,R.id.pointSize,R.id.pointBudget,R.id.moreTools};String[] labels={"X7 · Сканер","＋ · Добавить TZF","ASC · Экспорт","R/M · Сканы","◎ · Измерить","P · Проекция","▦ · Сетка","CUT · Сечение","•• · Размер","AUTO · Точки","⋯ · Инструменты"};for(int i=0;i<ids.length;i++){Button button=findViewById(ids[i]);button.setVisibility(View.VISIBLE);button.setText(labels[i]);button.setTextSize(11);button.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);button.setPadding(dp(12),0,dp(6),0);button.getLayoutParams().width=FrameLayout.LayoutParams.MATCH_PARENT;button.getLayoutParams().height=dp(48);button.requestLayout();}FrameLayout.LayoutParams appBar=(FrameLayout.LayoutParams)findViewById(R.id.appBar).getLayoutParams();appBar.leftMargin=dp(160);findViewById(R.id.appBar).setLayoutParams(appBar);FrameLayout.LayoutParams pair=(FrameLayout.LayoutParams)pairCard.getLayoutParams();pair.leftMargin=dp(160);pairCard.setLayoutParams(pair);}updatePointControlLabels();updatePairCardVisibility();}
    private void updatePointControlLabels(){if(pointSizeButton==null||budgetButton==null)return;pointSizeButton.setText(expandedLayout?"•• · Размер: "+project.pointSize:"•• "+project.pointSize);budgetButton.setText(expandedLayout?"Точки · "+budgetLabel(project.pointBudget):budgetLabel(project.pointBudget));}
    private void sizeOverlays(){findViewById(R.id.viewportContainer).post(()->{if(expandedLayout){int height=Math.max(dp(260),findViewById(R.id.viewportContainer).getHeight()-dp(140));for(View panel:new View[]{scanPanel,settingsPanel}){FrameLayout.LayoutParams params=(FrameLayout.LayoutParams)panel.getLayoutParams();params.width=dp(360);params.height=height;params.gravity=Gravity.END|Gravity.BOTTOM;params.rightMargin=dp(8);params.bottomMargin=dp(62);panel.setLayoutParams(params);}}else{int max=Math.round(findViewById(R.id.viewportContainer).getHeight()*.35f),cap=dp(220),height=Math.min(cap,max);scanPanel.getLayoutParams().height=height;settingsPanel.getLayoutParams().height=height;scanPanel.requestLayout();settingsPanel.requestLayout();}});}
    private void updatePairCardVisibility(){if(pairCard==null||status==null)return;boolean show=project.scanCount()>0||x7Running;pairCard.setVisibility(show?View.VISIBLE:View.GONE);FrameLayout.LayoutParams params=(FrameLayout.LayoutParams)status.getLayoutParams();params.leftMargin=expandedLayout?dp(168):dp(68);params.bottomMargin=show?dp(64):dp(16);status.setLayoutParams(params);}
    private void togglePanel(View show,View hide){hide.setVisibility(View.GONE);show.setVisibility(show.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);}
    private void showStitchingMenu(View anchor){
        PopupMenu menu=new PopupMenu(this,anchor);
        menu.getMenu().add(0,4,0,manipulatorMode?"Выйти из манипулятора":"Манипулятор — совместить сверху");
        menu.getMenu().add(0,1,1,"Авто — поиск совпадения");
        menu.getMenu().add(0,2,2,"Уточнение — довести текущую позу");
        ProjectModel.Node moving=project.findNode(project.movingNodeId);if(moving instanceof ProjectModel.Group&&scansUnder(moving,true).size()>1)menu.getMenu().add(0,3,2,"Группа — сшить все станции");
        menu.setOnMenuItemClickListener(item->{if(item.getItemId()==4){if(manipulatorMode)exitManipulatorMode(true);else enterManipulatorMode();}else if(item.getItemId()==1)startDeepRegistration();else if(item.getItemId()==2)startRegistration();else if(item.getItemId()==3)startGroupRegistration();return true;});
        menu.show();
    }
    private void enterManipulatorMode(){ProjectModel.Node reference=project.findNode(project.referenceNodeId),moving=project.findNode(project.movingNodeId);if(!project.canRegister()||!nodesReady(reference,moving)){status.setText("Выберите готовые R и M");return;}rejectRegistrationCandidate();manipulatorMode=true;scanPanel.setVisibility(View.GONE);settingsPanel.setVisibility(View.GONE);setOrbitMode(false);orbitModeButton.setVisibility(View.GONE);cloud.setTopDownManipulator(true);renderRegistrationState(RegistrationUiState.idle());status.setText("Манипулятор: внутри круга — двигать XY, кольцо — вращать · затем Сшить");}
    private void exitManipulatorMode(boolean announce){if(!manipulatorMode)return;manipulatorMode=false;cloud.setTopDownManipulator(false);setOrbitMode(false);orbitModeButton.setVisibility(View.VISIBLE);renderRegistrationState(RegistrationUiState.idle());if(announce)status.setText("Манипулятор выключен · ракурс восстановлен");}
    private void showToolsMenu(View anchor){PopupMenu menu=new PopupMenu(this,anchor);menu.getMenu().add(0,108,0,"Сохранить проект");menu.getMenu().add(0,109,1,"Показать всё");menu.getMenu().add(0,101,2,"Экспортировать ASC");menu.getMenu().add(0,102,3,"Измерение");menu.getMenu().add(0,103,4,"Сменить проекцию");menu.getMenu().add(0,104,5,"Показать / скрыть сетку");menu.getMenu().add(0,105,6,"Размер точек: "+project.pointSize);menu.getMenu().add(0,106,7,"Количество точек: "+budgetLabel(project.pointBudget));android.view.MenuItem stitching=menu.getMenu().add(0,107,8,"Сшивка R/M…");ProjectModel.Node reference=project.findNode(project.referenceNodeId),moving=project.findNode(project.movingNodeId);stitching.setEnabled(stitchingActionsEnabled&&project.canRegister()&&nodesReady(reference,moving));menu.setOnMenuItemClickListener(item->{int id=item.getItemId();if(id==108)findViewById(R.id.saveProject).performClick();else if(id==109)findViewById(R.id.compactFit).performClick();else if(id==101)findViewById(R.id.exportAsc).performClick();else if(id==102)findViewById(R.id.measure).performClick();else if(id==103)findViewById(R.id.compactProjection).performClick();else if(id==104)findViewById(R.id.grid).performClick();else if(id==105)findViewById(R.id.pointSize).performClick();else if(id==106)findViewById(R.id.pointBudget).performClick();else if(id==107)showStitchingMenu(anchor);return true;});menu.show();}

    private void promptX7Connection(){
        android.content.SharedPreferences preferences=getSharedPreferences("x7",MODE_PRIVATE);
        LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);int pad=dp(18);form.setPadding(pad,0,pad,0);
        EditText host=new EditText(this);host.setHint("IP X7");host.setText(preferences.getString("host","192.168.43.1"));form.addView(host);
        EditText user=new EditText(this);user.setHint("FTP логин X7");user.setText(preferences.getString("user","media"));form.addView(user);
        EditText password=new EditText(this);password.setHint("FTP пароль X7");password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);password.setText(preferences.getString("password","media"));form.addView(password);
        new AlertDialog.Builder(this).setTitle("Подключить Trimble X7").setMessage("Телефон должен быть подключён к Wi‑Fi X7.").setView(form).setNegativeButton("Отмена",null).setPositiveButton("Подключить",(d,w)->{
            String h=host.getText().toString().trim(),u=user.getText().toString().trim(),p=password.getText().toString();
            if(h.isEmpty()||u.isEmpty()||p.isEmpty()){status.setText("Укажите IP и FTP доступ X7");return;}
            preferences.edit().putString("host",h).putString("user",u).putString("password",p).apply();connectX7(new TrimbleX7Client(h,u,p));
        }).show();
    }

    private void connectX7(TrimbleX7Client client){setX7Running(true);status.setText("X7: подключение…");worker.execute(()->{try{client.projects();runOnUiThread(()->showX7MainMenu(client));}catch(Exception error){finishX7Error(error);}});}
    private void showX7MainMenu(TrimbleX7Client client){new AlertDialog.Builder(this).setTitle("Trimble X7 подключён").setItems(new String[]{"Новый скан","Загрузить скан","Посмотреть скан","Отключить"},(d,which)->{if(which==3){setX7Running(false);status.setText("X7: отключено");}else chooseX7Project(client,which);}).setOnCancelListener(d->setX7Running(false)).show();}
    private void chooseX7Project(TrimbleX7Client client,int action){
        status.setText("X7: получаем проекты…");worker.execute(()->{try{List<TrimbleX7Client.Project> projects=client.projects();int extra=action==0?1:0;String[] labels=new String[projects.size()+extra];if(extra==1)labels[0]="＋ Новый проект X7";for(int i=0;i<projects.size();i++)labels[i+extra]=projects.get(i).name;runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Проект на Trimble X7").setItems(labels,(d,which)->{if(extra==1&&which==0){promptNewX7Project(client);return;}TrimbleX7Client.Project selected=projects.get(which-extra);if(action==0)runX7Scan(client,selected);else chooseReadyX7Scan(client,selected,action==2);}).setOnCancelListener(d->setX7Running(false)).show());}catch(Exception error){finishX7Error(error);}});
    }

    private void showX7ProjectActions(TrimbleX7Client client,TrimbleX7Client.Project scannerProject){new AlertDialog.Builder(this).setTitle(scannerProject.name).setItems(new String[]{"Новый скан","Загрузить скан в проект","Посмотреть скан"},(d,which)->{if(which==0)runX7Scan(client,scannerProject);else chooseReadyX7Scan(client,scannerProject,which==2);}).setOnCancelListener(d->setX7Running(false)).show();}

    private void promptNewX7Project(TrimbleX7Client client){EditText name=new EditText(this);name.setSingleLine(true);name.setText(project.name);new AlertDialog.Builder(this).setTitle("Новый проект на X7").setMessage("X7 создаст его при старте первого скана.").setView(name).setNegativeButton("Отмена",(d,w)->setX7Running(false)).setPositiveButton("Создать и сканировать",(d,w)->{String suffix=name.getText().toString().trim();if(suffix.isEmpty()){setX7Running(false);status.setText("Укажите имя проекта X7");return;}String prefix=new java.text.SimpleDateFormat("yyyy-MM-dd_HH-mm-ss_",Locale.US).format(new java.util.Date());runX7Scan(client,new TrimbleX7Client.Project(-1,1,prefix+suffix,UUID.randomUUID().toString()));}).show();}

    private void runX7Scan(TrimbleX7Client client,TrimbleX7Client.Project scannerProject){
        worker.execute(()->{try{
            runOnUiThread(()->status.setText("X7: запускаем скан…"));
            org.json.JSONObject configuration=client.configuration(scannerProject);if(scannerProject.id<0){configuration.put("projectName",scannerProject.name);configuration.put("projectUUID",scannerProject.uuid);configuration.put("nextProjectScanID",1);configuration.put("nextProjectAreaScanID",0);}TrimbleX7Client.Task task=client.start(configuration);
            if(task.id<0)throw new IOException("X7 не вернул ID задачи");
            activeX7Client=client;activeX7TaskId=task.id;x7CancelRequested=false;
            long deadline=System.currentTimeMillis()+12*60_000L;
            while(true){if(x7CancelRequested)throw new IOException("скан отменён");if(System.currentTimeMillis()>deadline)throw new IOException("превышено время ожидания скана");try{TrimbleX7Client.Task current=client.task(task.id);if(current.failed())throw new IOException("X7 сообщил ошибку сканирования");final int percent=Math.max(0,Math.min(100,current.percent));runOnUiThread(()->updateX7Progress(current.state,percent));if(current.complete()){task=current;break;}}catch(TrimbleX7Client.HttpStatusException gone){if(gone.code!=410)throw gone;runOnUiThread(()->updateX7Progress("завершение",100));break;}Thread.sleep(1_000);}
            downloadX7Scan(client,scannerProject,task.scanId);
        }catch(Exception error){finishX7Error(error);}});
    }

    private void chooseReadyX7Scan(TrimbleX7Client client,TrimbleX7Client.Project scannerProject,boolean preview){status.setText("X7: получаем сканы…");worker.execute(()->{try{List<TrimbleX7Client.Scan> scans=client.scans(scannerProject);if(scans.isEmpty())throw new IOException("в проекте X7 нет готовых TZF");String[] labels=new String[scans.size()];for(int i=0;i<scans.size();i++){TrimbleX7Client.Scan scan=scans.get(i);labels[i]="Скан "+scan.id+" · "+scan.file+" · "+String.format(Locale.US,"%.1f MB",scan.size/1048576d);}runOnUiThread(()->{if(preview){new AlertDialog.Builder(this).setTitle("Готовые сканы X7").setItems(labels,(d,which)->downloadPreviewX7Scan(client,scannerProject,scans.get(which))).setOnCancelListener(d->setX7Running(false)).show();return;}boolean[] checked=new boolean[scans.size()];new AlertDialog.Builder(this).setTitle("Готовые сканы X7").setMultiChoiceItems(labels,checked,(d,which,on)->checked[which]=on).setNegativeButton("Добавить все",(d,w)->downloadX7Scans(client,scannerProject,scans)).setPositiveButton("Добавить выбранные",(d,w)->{List<TrimbleX7Client.Scan> selected=new ArrayList<>();for(int i=0;i<scans.size();i++)if(checked[i])selected.add(scans.get(i));if(selected.isEmpty()){setX7Running(false);status.setText("X7: сканы не выбраны");}else downloadX7Scans(client,scannerProject,selected);}).show();});}catch(Exception error){finishX7Error(error);}});}
    private void downloadX7Scans(TrimbleX7Client client,TrimbleX7Client.Project project,List<TrimbleX7Client.Scan> scans){worker.execute(()->{try{for(TrimbleX7Client.Scan scan:scans)downloadX7Scan(client,project,scan.id);}catch(Exception error){finishX7Error(error);}});}
    private void downloadPreviewX7Scan(TrimbleX7Client client,TrimbleX7Client.Project scannerProject,TrimbleX7Client.Scan scan){if(previewInFlight){status.setText("X7: предпросмотр уже открыт");return;}previewInFlight=true;worker.execute(()->{try{File file=new File(getCacheDir(),"x7-preview-"+scan.id+".tzf");client.download(scannerProject,scan,file,(phase,percent)->runOnUiThread(()->{x7Progress.setProgress(percent);status.setText("X7: "+phase+" "+percent+"%");}));runOnUiThread(()->{Intent intent=new Intent(this,MainActivity.class);intent.putExtra(EXTRA_X7_PREVIEW_PATH,file.getAbsolutePath());startActivityForResult(intent,PREVIEW_X7);setX7Running(false);});}catch(Exception error){previewInFlight=false;finishX7Error(error);}});}
    private void downloadX7Scan(TrimbleX7Client client,TrimbleX7Client.Project scannerProject,int scanId)throws Exception{TrimbleX7Client.Scan scan=null;for(int attempt=0;attempt<60;attempt++){scan=client.scan(scannerProject,scanId);if(scan.size>0&&!scan.file.isEmpty())break;Thread.sleep(1_000);}if(scan==null||scan.size<=0)throw new IOException("X7 ещё не подготовил TZF");String filename=new File(scan.file).getName();if(!filename.toLowerCase(Locale.ROOT).endsWith(".tzf"))throw new IOException("X7 вернул недопустимое имя TZF");File temporary=new File(getCacheDir(),"x7-download-"+scan.id+".tzf");client.download(scannerProject,scan,temporary,(phase,percent)->runOnUiThread(()->{x7Progress.setProgress(percent);status.setText("X7: "+phase+" "+percent+"%");}));Uri stored=stageX7File(temporary,"x7-"+scan.id+"-"+filename);runOnUiThread(()->{ProjectModel.Scan local=rememberScan(stored,filename);changed();tree.refresh();decodeScene(stored,local);status.setText("X7: файл добавлен в проект");setX7Running(false);});}
    private Uri stageX7File(File temporary,String filename)throws IOException{File directory=new File(new File(new File(getFilesDir(),"projects"),project.id),"staging");if(!directory.exists()&&!directory.mkdirs())throw new IOException("не удалось создать staging проекта");File output=new File(directory,filename);try(InputStream input=new java.io.FileInputStream(temporary);FileOutputStream stream=new FileOutputStream(output,false)){byte[] buffer=new byte[64*1024];int count;while((count=input.read(buffer))!=-1)stream.write(buffer,0,count);}temporary.delete();return Uri.fromFile(output);}

    private void cancelX7Scan(){TrimbleX7Client client=activeX7Client;int task=activeX7TaskId;if(!x7Running||client==null||task<0)return;x7CancelRequested=true;cancelX7Button.setEnabled(false);status.setText("X7: отменяем скан…");new Thread(()->{try{client.cancel(task);}catch(Exception error){runOnUiThread(()->status.setText("X7: отмена не принята: "+error.getMessage()));}},"x7-cancel").start();}
    private void updateX7Progress(String state,int percent){x7Progress.setProgress(percent);status.setText("X7: "+state+" · "+percent+"%");}
    private void finishX7Error(Exception error){runOnUiThread(()->{setX7Running(false);String message=error.getMessage();status.setText("X7: "+(message==null?"ошибка подключения":message));});}
    private void setX7Running(boolean running){x7Running=running;activeX7Client=running?activeX7Client:null;activeX7TaskId=running?activeX7TaskId:-1;if(scanX7Button!=null)scanX7Button.setEnabled(!running);if(x7Progress!=null){x7Progress.setVisibility(running?View.VISIBLE:View.GONE);if(!running)x7Progress.setProgress(0);}if(cancelX7Button!=null){cancelX7Button.setVisibility(running?View.VISIBLE:View.GONE);cancelX7Button.setEnabled(running);}updatePairCardVisibility();}

    private void selectTzf(){Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.setType("*/*");intent.addCategory(Intent.CATEGORY_OPENABLE);intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(intent,PICK_TZF);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==PREVIEW_X7){previewInFlight=false;return;}if(request==CREATE_ASC){if(result==RESULT_OK&&data!=null&&data.getData()!=null)exportAsc(data.getData());return;}if(request!=PICK_TZF||result!=RESULT_OK||data==null)return;List<Uri> uris=new ArrayList<>();ClipData clip=data.getClipData();if(clip!=null)for(int i=0;i<clip.getItemCount();i++)uris.add(clip.getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());int added=0;for(Uri uri:uris){String name=displayName(uri);if(!name.toLowerCase(Locale.ROOT).endsWith(".tzf")){status.setText("Пропущен не-TZF файл: "+name);continue;}try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}ProjectModel.Scan scan=rememberScan(uri,name);if(scan.loadState!=ProjectModel.Scan.READY){decodeScene(uri,scan);added++;}}changed();tree.refresh();status.setText("Добавлено в очередь: "+added);}

    private ProjectModel.Scan rememberScan(Uri uri,String name){for(ProjectModel.Scan scan:allScans())if(uri.toString().equals(scan.uri))return scan;ProjectModel.Scan scan=new ProjectModel.Scan(UUID.randomUUID().toString(),name);scan.uri=uri.toString();scan.color=nextScanColor();project.root.add(scan);return scan;}
    private int nextScanColor(){HashSet<Integer> used=new HashSet<>();for(ProjectModel.Scan scan:allScans())used.add(scan.color);int[] choices=new int[SCAN_COLORS.length];int count=0;for(int color:SCAN_COLORS)if(!used.contains(color))choices[count++]=color;if(count==0){System.arraycopy(SCAN_COLORS,0,choices,0,SCAN_COLORS.length);count=choices.length;}return choices[random.nextInt(count)];}
    private String displayName(Uri uri){try(android.database.Cursor c=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())return c.getString(0);}catch(Exception ignored){}String name=uri.getLastPathSegment();return name==null?"Scan.tzf":name.substring(Math.max(name.lastIndexOf('/')+1,name.lastIndexOf(':')+1));}

    private void decodeScene(Uri uri,ProjectModel.Scan scan){AtomicInteger counter=sceneGenerations.computeIfAbsent(scan.id,k->new AtomicInteger());int generation=counter.incrementAndGet();scan.loadState=ProjectModel.Scan.LOADING;scan.loadError="";tree.refresh();worker.execute(()->{try{File local=copyToCache(uri,"scene-"+scan.id+".tzf");if(project.findNode(scan.id)==null)return;localFiles.put(scan.id,local);NativePreviewSession old=sessions.remove(scan.id);if(old!=null)old.close();NativePreviewSession session=new NativePreviewSession(local.getAbsolutePath());sessions.put(scan.id,session);scan.sourcePointCount=session.sourcePointCount();boolean poseChanged=project.initializeEmbeddedPose(scan,session.initialPose());if(poseChanged)runOnUiThread(this::changed);int quota=scanQuota(scan);session.prepare(quota);boolean first=true;int published=0;while(counter.get()==generation&&project.findNode(scan.id)!=null){float[] chunk=session.nextChunk(100_000);if(chunk.length==0)break;boolean reset=first;first=false;published+=chunk.length/3;float[] world=scan.worldTransform();cloud.appendSceneCloud(scan.id,chunk,world,scan.color,isEffectivelyVisible(scan),reset);}if(counter.get()!=generation||project.findNode(scan.id)==null)return;int total=published;scan.loadState=ProjectModel.Scan.READY;runOnUiThread(()->{if(counter.get()!=generation||project.findNode(scan.id)==null)return;tree.refresh();syncScene();updateRoleUi();status.setText(scan.name+": "+total+" точек");});}catch(InterruptedException stopped){Thread.currentThread().interrupt();}catch(Exception error){scan.loadState=ProjectModel.Scan.ERROR;scan.loadError=error.getMessage();runOnUiThread(()->{if(counter.get()==generation&&project.findNode(scan.id)!=null){tree.refresh();status.setText(scan.name+" недоступен: "+error.getMessage());}});}});}
    private void handleSceneGpuError(String scanId,String message){AtomicInteger generation=sceneGenerations.get(scanId);if(generation!=null)generation.incrementAndGet();ProjectModel.Node node=project.findNode(scanId);if(!(node instanceof ProjectModel.Scan))return;ProjectModel.Scan scan=(ProjectModel.Scan)node;scan.loadState=ProjectModel.Scan.ERROR;scan.loadError=message;tree.refresh();status.setText(scan.name+": "+message);}
    private void restoreProjectScans(){for(ProjectModel.Scan scan:allScans())if(scan.uri!=null&&!scan.uri.isEmpty())decodeScene(Uri.parse(scan.uri),scan);}
    private void reloadAll(){for(ProjectModel.Scan scan:allScans())if(scan.uri!=null&&!scan.uri.isEmpty())decodeScene(Uri.parse(scan.uri),scan);}
    private File copyToCache(Uri uri,String name)throws IOException{File target=new File(getCacheDir(),name);InputStream source="file".equals(uri.getScheme())?new java.io.FileInputStream(new File(uri.getPath())):getContentResolver().openInputStream(uri);try(InputStream input=source;FileOutputStream output=new FileOutputStream(target,false)){if(input==null)throw new IOException("нет доступа к выбранному файлу");byte[] buffer=new byte[1024*1024];int count;while((count=input.read(buffer))!=-1)output.write(buffer,0,count);}return target;}

    private void syncScene(){List<ProjectModel.Scan> scans=allScans();String[] live=new String[scans.size()];java.util.HashSet<String> keep=new java.util.HashSet<>();for(int i=0;i<scans.size();i++){ProjectModel.Scan scan=scans.get(i);live[i]=scan.id;keep.add(scan.id);cloud.setSceneCloudVisible(scan.id,isEffectivelyVisible(scan));cloud.setSceneCloudTransform(scan.id,scan.worldTransform());}for(String id:new ArrayList<>(sceneGenerations.keySet()))if(!keep.contains(id)){AtomicInteger generation=sceneGenerations.remove(id);if(generation!=null)generation.incrementAndGet();NativePreviewSession session=sessions.remove(id);if(session!=null)session.close();localFiles.remove(id);}cloud.retainSceneClouds(live);ProjectModel.Node moving=project.findNode(project.movingNodeId);cloud.setActiveSceneTarget(moving==null?null:moving.id,scanIds(moving),moving==null?null:moving.worldTransform());updatePairCardVisibility();}
    private boolean isEffectivelyVisible(ProjectModel.Node node){for(ProjectModel.Node n=node;n!=null;n=n.parent())if(!n.visible)return false;return true;}
    private List<ProjectModel.Scan> allScans(){List<ProjectModel.Scan> out=new ArrayList<>();collectScans(project.root,out,false);return out;}
    private List<ProjectModel.Scan> readyScans(){List<ProjectModel.Scan> out=new ArrayList<>();collectScans(project.root,out,true);return out;}
    private void collectScans(ProjectModel.Group group,List<ProjectModel.Scan> out,boolean readyOnly){for(ProjectModel.Node node:group.children())if(node instanceof ProjectModel.Scan){ProjectModel.Scan scan=(ProjectModel.Scan)node;if(!readyOnly||(scan.loadState==ProjectModel.Scan.READY&&isEffectivelyVisible(scan)))out.add(scan);}else collectScans((ProjectModel.Group)node,out,readyOnly);}
    private String[] scanIds(ProjectModel.Node node){if(node==null)return new String[0];List<ProjectModel.Scan> scans=scansUnder(node,false);String[] ids=new String[scans.size()];for(int i=0;i<ids.length;i++)ids[i]=scans.get(i).id;return ids;}
    private List<ProjectModel.Scan> scansUnder(ProjectModel.Node node,boolean readyVisible){List<ProjectModel.Scan> out=new ArrayList<>();if(node instanceof ProjectModel.Scan){ProjectModel.Scan scan=(ProjectModel.Scan)node;if(!readyVisible||(scan.loadState==ProjectModel.Scan.READY&&isEffectivelyVisible(scan)))out.add(scan);}else if(node instanceof ProjectModel.Group)collectScans((ProjectModel.Group)node,out,readyVisible);return out;}

    private void updateRoleUi(){ProjectModel.Node reference=project.findNode(project.referenceNodeId),moving=project.findNode(project.movingNodeId);referenceLabel.setText("R  "+nodeLabel(reference));movingLabel.setText("M  "+nodeLabel(moving));stitchMenuButton.setEnabled(true);if(moving==null)transformSummary.setText("M не выбран");else{float[] t=moving.worldTransform();transformSummary.setText(String.format(Locale.US,"X %.3f  Y %.3f  Z %.3f · RZ %.2f°",t[0],t[1],t[2],t[3]));}cloud.setActiveSceneTarget(moving==null?null:moving.id,scanIds(moving),moving==null?null:moving.worldTransform());updatePairCardVisibility();}
    private String nodeLabel(ProjectModel.Node node){return node==null?"не выбран":node.name+(node instanceof ProjectModel.Group?" · связка "+node.scanCount():"");}
    private boolean nodesReady(ProjectModel.Node...nodes){for(ProjectModel.Node node:nodes)if(node==null||scansUnder(node,true).isEmpty())return false;return true;}

    private void applyMovingWorldTransform(String targetNodeId,float[] world){if(targetNodeId==null||!targetNodeId.equals(project.movingNodeId))return;ProjectModel.Node moving=project.findNode(targetNodeId);if(moving==null||moving.id.equals(project.referenceNodeId))return;float[] local=moving.parent()==null?world:ProjectModel.relative(moving.parent().worldTransform(),world);System.arraycopy(local,0,moving.transform,0,4);for(ProjectModel.Scan scan:scansUnder(moving,false))cloud.setSceneCloudTransform(scan.id,scan.worldTransform());}
    private void resetMoving(){ProjectModel.Node moving=project.findNode(project.movingNodeId);if(moving==null){status.setText("Сначала выберите M");return;}Arrays.fill(moving.transform,0);changed();syncScene();updateRoleUi();}
    private String snapshotKey(){return "transform-"+project.id+"-"+project.movingNodeId;}
    private void saveMovingSnapshot(){ProjectModel.Node moving=project.findNode(project.movingNodeId);if(moving==null){status.setText("Сначала выберите M");return;}getPreferences(MODE_PRIVATE).edit().putString(snapshotKey(),join(moving.transform)).apply();status.setText("Трансформация M сохранена");}
    private void restoreMovingSnapshot(){ProjectModel.Node moving=project.findNode(project.movingNodeId);if(moving==null){status.setText("Сначала выберите M");return;}String[] p=getPreferences(MODE_PRIVATE).getString(snapshotKey(),"").split(",");if(p.length!=4){status.setText("Сохранённой трансформации нет");return;}try{for(int i=0;i<4;i++)moving.transform[i]=Float.parseFloat(p[i]);changed();syncScene();updateRoleUi();status.setText("Трансформация восстановлена");}catch(NumberFormatException e){status.setText("Сохранённая трансформация повреждена");}}
    private String join(float[] values){return values[0]+","+values[1]+","+values[2]+","+values[3];}

    private void startRegistration(){ProjectModel.Node reference=project.findNode(project.referenceNodeId),moving=project.findNode(project.movingNodeId);if(!project.canRegister()||!nodesReady(reference,moving)){status.setText("Выберите готовые R и M");return;}int generation=registrationGeneration.incrementAndGet();float[] movingWorld=moving.worldTransform();renderRegistrationState(RegistrationUiState.running(RegistrationUiState.Stage.PREPARING,5,"Подготовка"));status.setText("Уточнение: подготовка выборок…");worker.execute(()->{try{float[] ref=buildRegistrationCloud(reference,null,generation,5,18);float[] mov=buildRegistrationCloud(moving,movingWorld,generation,18,35);updateRegistrationProgress(generation,RegistrationUiState.Stage.REFINING,35,"Уточнение: точная доводка…");float[] pivot=centerOf(mov);float[] solverInitial=RegistrationTransform.toPivot(movingWorld,pivot);RegistrationResult result=TzfNative.registerPointClouds(ref,mov,solverInitial,DEFAULT_RMS_LIMIT,DEFAULT_P95_LIMIT);runOnUiThread(()->finishRegistration(generation,result,pivot));}catch(Exception error){runOnUiThread(()->{if(registrationGeneration.get()==generation){setRegistrationRunning(false);status.setText("Ошибка уточнения: "+error.getMessage());}});}});}
    private void startDeepRegistration(){ProjectModel.Node reference=project.findNode(project.referenceNodeId),moving=project.findNode(project.movingNodeId);if(!project.canRegister()||!nodesReady(reference,moving)){status.setText("Выберите готовые R и M");return;}rejectRegistrationCandidate();int generation=registrationGeneration.incrementAndGet();float[] movingWorld=moving.worldTransform();float[] embeddedWorld=embeddedMovingWorld(reference,moving);boolean embeddedInitial=embeddedWorld!=null;renderRegistrationState(RegistrationUiState.running(RegistrationUiState.Stage.PREPARING,5,"Подготовка"));status.setText(embeddedInitial?"Авто: используем позу X7…":"Авто: подготовка выборок…");worker.execute(()->{try{float[] ref=buildRegistrationCloud(reference,null,generation,5,15);float[] mov=buildRegistrationCloud(moving,movingWorld,generation,15,25);updateRegistrationProgress(generation,embeddedInitial?RegistrationUiState.Stage.REFINING:RegistrationUiState.Stage.SEARCHING,25,embeddedInitial?"Авто: точная доводка от позы X7…":"Авто: признаки, гипотезы, проверка и уточнение…");float[] pivot=centerOf(mov);RegistrationResult result;if(embeddedInitial){float[] solverInitial=RegistrationTransform.toPivot(embeddedWorld,pivot);result=TzfNative.registerPointClouds(ref,mov,solverInitial,DEFAULT_RMS_LIMIT,DEFAULT_P95_LIMIT);}else result=TzfNative.registerPointCloudsGlobal(ref,mov,DEFAULT_RMS_LIMIT,DEFAULT_P95_LIMIT);runOnUiThread(()->finishDeepRegistration(generation,result,pivot,movingWorld));}catch(Exception error){runOnUiThread(()->{if(registrationGeneration.get()==generation){renderRegistrationState(RegistrationUiState.error(error.getMessage()));status.setText("Ошибка авто-сшивки: "+error.getMessage());}});}});}

    private boolean hasEmbeddedPose(ProjectModel.Node node){List<ProjectModel.Scan> scans=scansUnder(node,true);if(scans.isEmpty())return false;for(ProjectModel.Scan scan:scans)if(!scan.embeddedPoseValid)return false;return true;}
    private float[] embeddedMovingWorld(ProjectModel.Node reference,ProjectModel.Node moving){if(!(reference instanceof ProjectModel.Scan)||!(moving instanceof ProjectModel.Scan)||!hasEmbeddedPose(reference)||!hasEmbeddedPose(moving))return null;ProjectModel.Scan ref=(ProjectModel.Scan)reference,mov=(ProjectModel.Scan)moving;float[] relative=ProjectModel.relative(ref.embeddedPose,mov.embeddedPose);if(!ProjectModel.informativeEmbeddedOffset(relative))return null;return ProjectModel.compose(ref.worldTransform(),relative);}
    private void startGroupRegistration(){ProjectModel.Node node=project.findNode(project.movingNodeId);if(!(node instanceof ProjectModel.Group)){status.setText("Выберите группу M");return;}List<ProjectModel.Scan> scans=scansUnder(node,true);if(scans.size()<2){status.setText("В группе нужно минимум два готовых скана");return;}rejectRegistrationCandidate();int generation=registrationGeneration.incrementAndGet();renderRegistrationState(RegistrationUiState.running(RegistrationUiState.Stage.PREPARING,2,"Групповая сшивка"));worker.execute(()->{try{List<float[]> clouds=new ArrayList<>();float[] initial=new float[scans.size()*4];for(int i=0;i<scans.size();++i){ProjectModel.Scan scan=scans.get(i);clouds.add(buildRegistrationCloud(scan,scan.worldTransform(),generation,2,20));System.arraycopy(scan.worldTransform(),0,initial,i*4,4);}List<Float> encoded=new ArrayList<>();int pairs=scans.size()*(scans.size()-1)/2,done=0;for(int i=0;i<scans.size();++i)for(int j=i+1;j<scans.size();++j){if(registrationGeneration.get()!=generation)throw new IOException("отменено");float[] relativeInitial=ProjectModel.relative(scans.get(i).embeddedPose,scans.get(j).embeddedPose);boolean embeddedPair=scans.get(i).embeddedPoseValid&&scans.get(j).embeddedPoseValid&&ProjectModel.informativeEmbeddedOffset(relativeInitial);updateRegistrationProgress(generation,embeddedPair?RegistrationUiState.Stage.REFINING:RegistrationUiState.Stage.SEARCHING,20+Math.round(60f*done++/Math.max(1,pairs)),"Группа: "+scans.get(i).name+" ↔ "+scans.get(j).name);float[] movingCloud=clouds.get(j),pivot=centerOf(movingCloud);RegistrationResult pair;if(embeddedPair)pair=TzfNative.registerPointClouds(clouds.get(i),movingCloud,RegistrationTransform.toPivot(relativeInitial,pivot),DEFAULT_RMS_LIMIT,DEFAULT_P95_LIMIT);else pair=TzfNative.registerPointCloudsGlobal(clouds.get(i),movingCloud,DEFAULT_RMS_LIMIT,DEFAULT_P95_LIMIT);if(!pair.accepted)continue;float[] relative=RegistrationTransform.fromPivot(pair.transform,pivot);encoded.add((float)i);encoded.add((float)j);for(float value:relative)encoded.add(value);encoded.add((float)Math.max(.05,pair.overlap/(1+pair.rms)));}float[] edges=new float[encoded.size()];for(int i=0;i<edges.length;++i)edges[i]=encoded.get(i);updateRegistrationProgress(generation,RegistrationUiState.Stage.VALIDATING,85,"Группа: оптимизация графа");float[] optimized=TzfNative.optimizePoseGraph(initial,edges,0);runOnUiThread(()->finishGroupRegistration(generation,scans,optimized));}catch(Exception error){runOnUiThread(()->{if(registrationGeneration.get()==generation){renderRegistrationState(RegistrationUiState.error(error.getMessage()));status.setText("Групповая сшивка: "+registrationReason(error.getMessage()));}});}});}
    private void finishGroupRegistration(int generation,List<ProjectModel.Scan> scans,float[] optimized){if(registrationGeneration.get()!=generation)return;candidateGraphScans=new ArrayList<>(scans);candidateGraphWorld=optimized;for(int i=0;i<scans.size();++i)cloud.setSceneCloudTransform(scans.get(i).id,Arrays.copyOfRange(optimized,i*4,i*4+4));renderRegistrationState(RegistrationUiState.preview("Группа"));status.setText("Групповой кандидат готов · "+scans.size()+" станций · применить?");}
    private void updateRegistrationProgress(int generation,RegistrationUiState.Stage stage,int progress,String message){runOnUiThread(()->{if(registrationGeneration.get()==generation){renderRegistrationState(RegistrationUiState.running(stage,progress,message));status.setText(message);}});}
    private float[] buildRegistrationCloud(ProjectModel.Node node,float[] relativeRoot,int generation,int progressStart,int progressEnd)throws IOException{List<ProjectModel.Scan> scans=scansUnder(node,true);if(scans.isEmpty())throw new IOException("в узле нет готовых видимых сканов");int quota=Math.max(20_000,60_000/scans.size());List<float[]> parts=new ArrayList<>();int total=0;for(int scanIndex=0;scanIndex<scans.size();scanIndex++){if(registrationGeneration.get()!=generation)throw new IOException("отменено");ProjectModel.Scan scan=scans.get(scanIndex);File file=localFiles.get(scan.id);if(file==null)throw new IOException(scan.name+" не загружен");float[] pose=relativeRoot==null?scan.worldTransform():ProjectModel.relative(relativeRoot,scan.worldTransform());try(NativePreviewSession session=new NativePreviewSession(file.getAbsolutePath())){session.prepare(quota);int prepared=0;while(registrationGeneration.get()==generation){float[] chunk=session.nextChunk(50_000);if(chunk.length==0)break;prepared+=chunk.length/3;applyPose(chunk,pose);parts.add(chunk);total+=chunk.length;float fraction=(scanIndex+Math.min(1f,prepared/(float)quota))/scans.size();int progress=progressStart+Math.round((progressEnd-progressStart)*fraction);updateRegistrationProgress(generation,RegistrationUiState.Stage.PREPARING,progress,"Подготовка: "+scan.name+" · "+prepared+" точек");}}}if(registrationGeneration.get()!=generation)throw new IOException("отменено");float[] result=new float[total];int offset=0;for(float[] part:parts){System.arraycopy(part,0,result,offset,part.length);offset+=part.length;}return result;}
    private static void applyPose(float[] xyz,float[] pose){double r=Math.toRadians(pose[3]),c=Math.cos(r),s=Math.sin(r);for(int i=0;i<xyz.length;i+=3){float x=xyz[i],y=xyz[i+1];xyz[i]=(float)(c*x-s*y)+pose[0];xyz[i+1]=(float)(s*x+c*y)+pose[1];xyz[i+2]+=pose[2];}}
    private static float[] centerOf(float[] xyz){return RegistrationTransform.centroid(xyz);}
    private void finishRegistration(int generation,RegistrationResult result,float[] pivot){if(registrationGeneration.get()!=generation)return;ProjectModel.Node moving=project.findNode(project.movingNodeId);if(!result.accepted||moving==null){setRegistrationRunning(false);status.setText("Уточнение: "+registrationReason(result.reason));return;}showRegistrationPreview(result,pivot,moving.worldTransform(),"Уточнение");}
    private void finishDeepRegistration(int generation,RegistrationResult result,float[] pivot,float[] originalWorld){if(registrationGeneration.get()!=generation)return;if(!result.accepted){renderRegistrationState(RegistrationUiState.error(result.reason));status.setText(String.format(Locale.US,"Авто: %s · RMS %.1f · P95 %.1f · перекрытие %.0f%% · доверие %.0f",registrationReason(result.reason),result.rms,result.p95,result.overlap*100,result.confidence));return;}showRegistrationPreview(result,pivot,originalWorld,"check registration".equals(result.reason)?"Авто · ПРОВЕРИТЬ":"Авто");}
    private void showRegistrationPreview(RegistrationResult result,float[] pivot,float[] originalWorld,String mode){candidateOriginalWorld=originalWorld.clone();candidateWorld=RegistrationTransform.fromPivot(result.transform,pivot);showRegistrationCandidate();renderRegistrationState(RegistrationUiState.preview("Кандидат"));status.setTextColor(getColor(R.color.text_secondary));status.setText(String.format(Locale.US,"%s · RMS %.1f мм · P95 %.1f мм · перекрытие %.0f%% · согласованность %.0f%% · доверие %.0f · Δ %.2f м / %.1f° · применить?",mode,result.rms,result.p95,result.overlap*100,result.consistency*100,result.confidence,result.correctionTranslation/1000.0,result.correctionYaw));}
    private void showRegistrationCandidate(){ProjectModel.Node moving=project.findNode(project.movingNodeId);if(moving==null||candidateWorld==null||candidateOriginalWorld==null)return;for(ProjectModel.Scan scan:scansUnder(moving,false)){float[] relative=ProjectModel.relative(candidateOriginalWorld,scan.worldTransform());cloud.setSceneCloudTransform(scan.id,ProjectModel.compose(candidateWorld,relative));}cloud.setActiveSceneTarget(moving.id,scanIds(moving),candidateWorld);}
    private void applyRegistrationCandidate(){if(candidateGraphScans!=null&&candidateGraphWorld!=null){for(int i=0;i<candidateGraphScans.size();++i){ProjectModel.Scan scan=candidateGraphScans.get(i);float[] world=Arrays.copyOfRange(candidateGraphWorld,i*4,i*4+4),local=ProjectModel.relative(scan.parent().worldTransform(),world);System.arraycopy(local,0,scan.transform,0,4);}candidateGraphScans=null;candidateGraphWorld=null;changed();syncScene();updateRoleUi();renderRegistrationState(RegistrationUiState.idle());status.setText("Групповая сшивка применена");return;}ProjectModel.Node moving=project.findNode(project.movingNodeId);if(moving==null||candidateWorld==null)return;float[] local=ProjectModel.relative(moving.parent().worldTransform(),candidateWorld);System.arraycopy(local,0,moving.transform,0,4);candidateWorld=candidateOriginalWorld=null;changed();syncScene();updateRoleUi();exitManipulatorMode(false);renderRegistrationState(RegistrationUiState.idle());status.setTextColor(getColor(R.color.text_secondary));status.setText("Кандидат сшивки применён");}
    private void rejectRegistrationCandidate(){if(candidateWorld==null&&candidateOriginalWorld==null&&candidateGraphScans==null)return;candidateWorld=candidateOriginalWorld=null;candidateGraphScans=null;candidateGraphWorld=null;syncScene();updateRoleUi();renderRegistrationState(RegistrationUiState.idle());status.setTextColor(getColor(R.color.text_secondary));status.setText("Кандидат отменён");}
    private void cancelRegistration(){registrationGeneration.incrementAndGet();TzfNative.cancelRegistration();setRegistrationRunning(false);status.setText("Сшивка отменена");}
    private void setRegistrationRunning(boolean running){renderRegistrationState(running?RegistrationUiState.running(RegistrationUiState.Stage.REFINING,50,"Точная сшивка"):RegistrationUiState.idle());}
    private void renderRegistrationState(RegistrationUiState state){stitchingActionsEnabled=state.actionsEnabled();stitchMenuButton.setEnabled(true);cancelButton.setVisibility(state.showCancel()?View.VISIBLE:View.GONE);applyCandidateButton.setVisibility(state.showDecision()?View.VISIBLE:View.GONE);rejectCandidateButton.setVisibility(state.showDecision()?View.VISIBLE:View.GONE);registrationProgress.setVisibility(state.showProgress()?View.VISIBLE:View.GONE);registrationProgress.setProgress(state.progress);boolean hideBase=state.running()||state.showDecision(),showManipulator=manipulatorMode&&!hideBase&&state.actionsEnabled();referenceLabel.setVisibility(hideBase||manipulatorMode?View.GONE:View.VISIBLE);movingLabel.setVisibility(hideBase||manipulatorMode?View.GONE:View.VISIBLE);findViewById(R.id.pairDetails).setVisibility(hideBase||manipulatorMode?View.GONE:View.VISIBLE);manipulatorStitchButton.setVisibility(showManipulator?View.VISIBLE:View.GONE);exitManipulatorButton.setVisibility(showManipulator?View.VISIBLE:View.GONE);}
    private String registrationReason(String reason){if(reason.contains("ambiguous"))return "найдено несколько неоднозначных совпадений";if(reason.contains("global hypothesis"))return "надёжная гипотеза не найдена — совместите сканы вручную";if(reason.contains("confidence"))return "низкая уверенность — совместите вручную и нажмите Уточнить";if(reason.contains("consistency"))return "соответствия нестабильны — уточните ручное положение";if(reason.contains("moved too far")||reason.contains("rotated too far"))return "уточнение ушло слишком далеко от ручной позиции";if(reason.contains("overlap"))return "недостаточное перекрытие";if(reason.contains("surface support"))return "недостаточно общих устойчивых поверхностей";if("degenerate geometry".equals(reason))return "неоднозначная геометрия";if(reason.contains("RMS"))return "RMS поверхности выше допуска";if(reason.contains("P95"))return "P95 поверхности выше допуска";if(reason.contains("points")||reason.contains("coverage"))return "недостаточно точек";return reason;}

    private void persistProjectFilesSafely(){String treeUri=getSharedPreferences("x7",MODE_PRIVATE).getString("storage_tree","");if(treeUri.isEmpty()){status.setText("Выберите папку хранения в настройках");return;}List<ProjectModel.Scan> projectScans=allScans();if(projectScans.isEmpty()){status.setText("В проекте нет сканов");return;}status.setText("Сохраняем проект…");worker.execute(()->{List<File> staged=new ArrayList<>();try{for(ProjectModel.Scan scan:projectScans)staged.add(copyToCache(Uri.parse(scan.uri),"persist-"+scan.id+".tzf"));DocumentFile root=DocumentFile.fromTreeUri(this,Uri.parse(treeUri));if(root==null)throw new IOException("папка хранения недоступна");DocumentFile projectFolder=findOrCreateDirectory(root,safeFileName(project.name));DocumentFile scansFolder=findOrCreateDirectory(projectFolder,"scans");List<String> newUris=new ArrayList<>();HashSet<String> usedNames=new HashSet<>();for(int i=0;i<projectScans.size();i++){String name=uniqueFileName(safeFileName(projectScans.get(i).name),usedNames);DocumentFile old=scansFolder.findFile(name);if(old!=null&&!old.delete())throw new IOException("не удалось заменить "+name);DocumentFile output=scansFolder.createFile("application/octet-stream",name);if(output==null)throw new IOException("не удалось создать "+name);copyFileToDocument(staged.get(i),output.getUri());newUris.add(output.getUri().toString());}runOnUiThread(()->{for(int i=0;i<projectScans.size();i++)projectScans.get(i).uri=newUris.get(i);changed();status.setText("Проект сохранён · "+projectScans.size()+" сканов");});}catch(Exception error){runOnUiThread(()->status.setText("Не удалось сохранить: "+error.getMessage()));}});}
    private DocumentFile findOrCreateDirectory(DocumentFile parent,String name)throws IOException{DocumentFile found=parent.findFile(name);if(found==null)found=parent.createDirectory(name);if(found==null||!found.isDirectory())throw new IOException("не удалось создать папку "+name);return found;}
    private static String safeFileName(String value){String safe=value==null?"scan.tzf":value.replaceAll("[\\\\/:*?\"<>|]","_").trim();return safe.isEmpty()?"scan.tzf":safe;}
    private static String uniqueFileName(String requested,HashSet<String> used){String base=requested.toLowerCase(Locale.ROOT).endsWith(".tzf")?requested.substring(0,requested.length()-4):requested,extension=".tzf",candidate=base+extension;int suffix=2;while(!used.add(candidate.toLowerCase(Locale.ROOT)))candidate=base+"-"+(suffix++)+extension;return candidate;}
    private void copyFileToDocument(File source,Uri destination)throws IOException{try(InputStream input=new java.io.FileInputStream(source);java.io.OutputStream output=getContentResolver().openOutputStream(destination,"w")){if(output==null)throw new IOException("папка недоступна для записи");byte[] buffer=new byte[1024*1024];int count;while((count=input.read(buffer))!=-1)output.write(buffer,0,count);}}
    private void chooseAscDestination(){Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT);intent.setType("text/plain");intent.addCategory(Intent.CATEGORY_OPENABLE);intent.putExtra(Intent.EXTRA_TITLE,project.name.replaceAll("[\\\\/:*?\"<>|]","_")+".asc");startActivityForResult(intent,CREATE_ASC);}
    private void exportAsc(Uri destination){List<ProjectModel.Scan> scans=allScans();if(scans.isEmpty()){status.setText("В проекте нет сканов");return;}status.setText("ASC: подготовка…");worker.execute(()->{long written=0;try(java.io.OutputStream output=getContentResolver().openOutputStream(destination,"w");BufferedWriter writer=new BufferedWriter(new OutputStreamWriter(output,java.nio.charset.StandardCharsets.UTF_8),1024*1024)){if(output==null)throw new IOException("не удалось открыть ASC");writer.write("# 3D Systems, Inc.\n# New Model\n");for(int index=0;index<scans.size();index++){ProjectModel.Scan scan=scans.get(index);File local=localFiles.get(scan.id);if(local==null)local=copyToCache(Uri.parse(scan.uri),"export-"+scan.id+".tzf");float[] pose=scan.worldTransform();try(NativePreviewSession session=new NativePreviewSession(local.getAbsolutePath())){long available=session.sourcePointCount();session.prepare((int)Math.min(Integer.MAX_VALUE,available));while(true){float[] chunk=session.nextChunk(100_000);if(chunk.length==0)break;applyPose(chunk,pose);StringBuilder lines=new StringBuilder(chunk.length*5);for(int i=0;i<chunk.length;i+=3)lines.append(Float.toString(chunk[i])).append(' ').append(Float.toString(chunk[i+1])).append(' ').append(Float.toString(chunk[i+2])).append('\n');writer.write(lines.toString());written+=chunk.length/3;long count=written;int scanNumber=index+1;runOnUiThread(()->status.setText("ASC: скан "+scanNumber+"/"+scans.size()+" · "+count+" точек"));}}}writer.flush();long total=written;runOnUiThread(()->status.setText("ASC сохранён · "+total+" точек"));}catch(Exception error){runOnUiThread(()->status.setText("Ошибка ASC: "+error.getMessage()));}});}
    private int scanQuota(ProjectModel.Scan scan){if(project.pointBudget==-2)return (int)Math.min(Integer.MAX_VALUE,Math.max(20_000L,scan.sourcePointCount));return Math.max(20_000,effectiveBudget()/Math.max(1,project.scanCount()));}
    private void sampleAutoBudget(float fps){if(project==null||project.pointBudget!=-1)return;int before=autoPointBudget.current(),after=autoPointBudget.sample(fps,false);if(after!=before){status.setText("AUTO: "+budgetLabel(after)+" · "+Math.round(fps)+" FPS");reloadAll();}}
    private int effectiveBudget(){return project.pointBudget<0?autoPointBudget.current():project.pointBudget;}
    private String budgetLabel(int budget){if(budget==-2)return "ALL";if(budget<0)return "AUTO";if(budget>=1_000_000)return String.format(Locale.US,"%.0fM",budget/1_000_000f);return budget/1000+"k";}
    private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
    private void changed(){project.touch(System.currentTimeMillis());if(previewMode)return;try{store.save(project);}catch(IOException error){status.setText("Не удалось сохранить проект: "+error.getMessage());}}
    private void navigateToProjects(){exitManipulatorMode(false);changed();finish();}
    @Override public void onBackPressed(){if(candidateWorld!=null||candidateGraphScans!=null){rejectRegistrationCandidate();return;}if(manipulatorMode){exitManipulatorMode(true);return;}if(scanPanel.getVisibility()==View.VISIBLE||settingsPanel.getVisibility()==View.VISIBLE){scanPanel.setVisibility(View.GONE);settingsPanel.setVisibility(View.GONE);return;}navigateToProjects();}
    @Override protected void onPause(){changed();cloud.onPause();super.onPause();}
    @Override protected void onResume(){super.onResume();if(cloud!=null)cloud.onResume();}
    @Override protected void onDestroy(){registrationGeneration.incrementAndGet();TzfNative.cancelRegistration();for(AtomicInteger generation:sceneGenerations.values())generation.incrementAndGet();for(NativePreviewSession session:sessions.values())session.close();sessions.clear();cloud.releaseSceneResources();worker.shutdownNow();if(previewMode&&previewFile!=null)previewFile.delete();super.onDestroy();}
}
