package ru.tzfviewer;

import android.util.Base64;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** HTTP/FTP client for an X7 connected through its own Wi-Fi access point. */
final class TrimbleX7Client {
    interface Progress { void update(String phase, int percent); }
    static final class Project { final int id,nextScanId; final String name,uuid; Project(JSONObject v){id=v.optInt("id");nextScanId=v.optInt("nextProjectScanID");name=v.optString("projectName");uuid=v.optString("projectUUID");} }
    static final class Task { final int id,scanId,percent; final String state; Task(JSONObject v){id=v.optInt("id",v.optInt("taskID",-1));scanId=v.optInt("scanID",-1);percent=v.optInt("percentage",0);state=v.optString("state","");} boolean failed(){String s=state.toLowerCase(Locale.ROOT);return s.contains("error")||s.contains("fail");} boolean complete(){return state.equalsIgnoreCase("finished")||state.equalsIgnoreCase("completed")||state.equalsIgnoreCase("done");} }
    static final class Scan { final int id,tzfId; final String file; final long size; Scan(JSONObject v){id=v.optInt("id",-1);tzfId=v.optInt("tzfId",-1);JSONObject t=v.optJSONObject("tzf");file=t==null?"":t.optString("file");size=t==null?0:t.optLong("fileSize");} }
    private final String host,user,password;
    TrimbleX7Client(String host,String user,String password){this.host=host.trim();this.user=user;this.password=password;}
    List<Project> projects() throws Exception {JSONArray values=new JSONArray(get("/api/v1/projects"));List<Project> r=new ArrayList<>();for(int i=0;i<values.length();i++)r.add(new Project(values.getJSONObject(i)));return r;}
    JSONObject configuration(Project project)throws Exception{return new JSONObject(get("/api/v1/scans/configuration/project?projectName="+Base64.encodeToString(project.name.getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP)));}
    Task start(JSONObject configuration)throws Exception{return new Task(new JSONObject(post("/api/v1/scans",configuration.toString())));}
    Task task(int id)throws Exception{String r=get("/api/v1/tasks/"+id+"?includeFinishedTask=true");if(r.trim().startsWith("[")){JSONArray a=new JSONArray(r);if(a.length()==0)throw new IOException("X7 не вернул задачу");return new Task(a.getJSONObject(0));}return new Task(new JSONObject(r));}
    Scan scan(Project project,int scanId)throws Exception{JSONArray a=new JSONArray(get("/api/v1/scans?projectName="+Base64.encodeToString(project.name.getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP)));Scan newest=null;for(int i=0;i<a.length();i++){Scan s=new Scan(a.getJSONObject(i));if(s.id==scanId)return s;if(newest==null||s.id>newest.id)newest=s;}if(newest==null)throw new IOException("X7 не вернул готовый скан");return newest;}
    void markForDownload(Scan scan)throws Exception{JSONObject b=new JSONObject();b.put("downloaded",false);b.put("file","");b.put("fileSize",0);b.put("id",scan.tzfId);b.put("nbPoints",0);put("/api/v1/tzfs/"+scan.tzfId,b.toString());}
    File download(Scan scan,File destination,Progress progress)throws Exception{if(scan.file.isEmpty()||scan.size<=0)throw new IOException("у выбранного скана нет TZF");if(destination.exists()&&!destination.delete())throw new IOException("не удалось заменить предыдущий TZF");try(Ftp ftp=new Ftp(host,user,password)){ftp.download("/ScanData/"+scan.file,destination,scan.size,progress);}if(destination.length()!=scan.size){destination.delete();throw new IOException("неполная загрузка TZF");}return destination;}
    private String get(String path)throws Exception{return request("GET",path,null);} private String post(String path,String body)throws Exception{return request("POST",path,body);} private String put(String path,String body)throws Exception{return request("PUT",path,body);}
    private String request(String method,String path,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL("http://"+host+":34567"+path).openConnection();c.setConnectTimeout(10_000);c.setReadTimeout(20_000);c.setRequestMethod(method);c.setRequestProperty("Accept","application/json");if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");byte[] b=body.getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(b.length);c.getOutputStream().write(b);}int code=c.getResponseCode();InputStream stream=code>=200&&code<300?c.getInputStream():c.getErrorStream();StringBuilder r=new StringBuilder();try(BufferedReader reader=new BufferedReader(new InputStreamReader(stream,StandardCharsets.UTF_8))){char[] chars=new char[4096];int count;while((count=reader.read(chars))!=-1)r.append(chars,0,count);}c.disconnect();if(code<200||code>=300)throw new IOException("X7 HTTP "+code+": "+r);return r.toString();}
    private static final class Ftp implements AutoCloseable { private final Socket control=new Socket();private final BufferedReader in;private final BufferedWriter out;
        Ftp(String host,String user,String password)throws Exception{control.connect(new InetSocketAddress(host,21),10_000);control.setSoTimeout(20_000);in=new BufferedReader(new InputStreamReader(control.getInputStream(),StandardCharsets.US_ASCII));out=new BufferedWriter(new OutputStreamWriter(control.getOutputStream(),StandardCharsets.US_ASCII));expect(220);command("USER "+user);expect(331);command("PASS "+password);expect(230);command("TYPE I");expect(200);}
        void download(String path,File target,long expected,Progress progress)throws Exception{command("PASV");String response=expect(227);int l=response.indexOf('('),r=response.indexOf(')',l);if(l<0||r<0)throw new IOException("X7 вернул некорректный passive FTP адрес");String[] p=response.substring(l+1,r).split(",");if(p.length!=6)throw new IOException("X7 вернул некорректный passive FTP порт");String address=p[0]+"."+p[1]+"."+p[2]+"."+p[3];int port=Integer.parseInt(p[4])*256+Integer.parseInt(p[5]);try(Socket data=new Socket()){data.connect(new InetSocketAddress(address,port),10_000);data.setSoTimeout(30_000);command("RETR "+path);expect(150);long received=0;try(BufferedInputStream source=new BufferedInputStream(data.getInputStream());FileOutputStream sink=new FileOutputStream(target)){byte[] b=new byte[64*1024];int count;while((count=source.read(b))!=-1){sink.write(b,0,count);received+=count;progress.update("Загрузка TZF",(int)Math.min(100,received*100/Math.max(1,expected)));}}expect(226);}}
        private void command(String value)throws IOException{out.write(value);out.write("\r\n");out.flush();} private String expect(int code)throws IOException{String line=in.readLine();if(line==null||!line.startsWith(Integer.toString(code)))throw new IOException("FTP X7: "+(line==null?"соединение закрыто":line));return line;} @Override public void close()throws Exception{try{command("QUIT");}catch(Exception ignored){}control.close();}
    }
}
