#include "tzf_geometry.h"
#include <algorithm>
#include <cmath>
#include <compare>
#include <map>
#include <numeric>
#include <queue>
namespace tzf { namespace {
struct V{double x{},y{},z{};}; struct C{int x{},y{},z{};auto operator<=>(const C&)const=default;}; struct A{V s{};std::size_t n{};}; struct S{V p{},n{};double planarity{};bool valid{};};
V v(Point p){return{p.x,p.y,p.z};} V add(V a,V b){return{a.x+b.x,a.y+b.y,a.z+b.z};} V sub(V a,V b){return{a.x-b.x,a.y-b.y,a.z-b.z};} V mul(V a,double s){return{a.x*s,a.y*s,a.z*s};} double dot(V a,V b){return a.x*b.x+a.y*b.y+a.z*b.z;} double len(V a){return std::sqrt(dot(a,a));} bool unit(V& a){double l=len(a);if(!std::isfinite(l)||l<1e-12)return false;a=mul(a,1/l);return true;} C cell(V p,double s){return{(int)std::floor(p.x/s),(int)std::floor(p.y/s),(int)std::floor(p.z/s)};}
std::array<double,3> eigenMin(double a[3][3]){double q[3][3]{{1,0,0},{0,1,0},{0,0,1}};for(int sweep=0;sweep<16;++sweep){int p=0,r=1;if(std::abs(a[0][2])>std::abs(a[p][r])){p=0;r=2;}if(std::abs(a[1][2])>std::abs(a[p][r])){p=1;r=2;}if(std::abs(a[p][r])<1e-14)break;double phi=.5*std::atan2(2*a[p][r],a[r][r]-a[p][p]),c=std::cos(phi),s=std::sin(phi);for(int k=0;k<3;++k){double x=a[p][k],y=a[r][k];a[p][k]=c*x-s*y;a[r][k]=s*x+c*y;}for(int k=0;k<3;++k){double x=a[k][p],y=a[k][r];a[k][p]=c*x-s*y;a[k][r]=s*x+c*y;}for(int k=0;k<3;++k){double x=q[k][p],y=q[k][r];q[k][p]=c*x-s*y;q[k][r]=s*x+c*y;}}int m=0;if(a[1][1]<a[m][m])m=1;if(a[2][2]<a[m][m])m=2;return{q[0][m],q[1][m],q[2][m]};}
std::vector<S> normals(const std::vector<Point>& pts,double voxel,double radius,std::size_t min,double threshold){std::map<C,std::vector<std::size_t>> g;for(std::size_t i=0;i<pts.size();++i)g[cell(v(pts[i]),voxel)].push_back(i);int reach=std::max(1,(int)std::ceil(radius/voxel));std::vector<S> out(pts.size());for(std::size_t i=0;i<pts.size();++i){V o=v(pts[i]);out[i].p=o;std::vector<V> ns;C base=cell(o,voxel);for(int z=-reach;z<=reach;++z)for(int y=-reach;y<=reach;++y)for(int x=-reach;x<=reach;++x){auto it=g.find({base.x+x,base.y+y,base.z+z});if(it!=g.end())for(auto j:it->second){V d=sub(v(pts[j]),o);if(dot(d,d)<=radius*radius)ns.push_back(v(pts[j]));}}if(ns.size()<min)continue;V c{};for(V p:ns)c=add(c,p);c=mul(c,1.0/ns.size());double cov[3][3]{};for(V p:ns){V d=sub(p,c);double e[3]{d.x,d.y,d.z};for(int r=0;r<3;++r)for(int k=0;k<3;++k)cov[r][k]+=e[r]*e[k];}double trace=cov[0][0]+cov[1][1]+cov[2][2];if(trace<=1e-15)continue;auto e=eigenMin(cov);V n{e[0],e[1],e[2]};if(!unit(n))continue;V cn{cov[0][0]*n.x+cov[0][1]*n.y+cov[0][2]*n.z,cov[1][0]*n.x+cov[1][1]*n.y+cov[1][2]*n.z,cov[2][0]*n.x+cov[2][1]*n.y+cov[2][2]*n.z};out[i].planarity=std::clamp(1-3*dot(n,cn)/trace,0.0,1.0);out[i].n=n;out[i].valid=out[i].planarity>=threshold;}return out;}
}
std::vector<Point> voxelCentroids(const std::vector<Point>& points,double size){if(!std::isfinite(size)||size<=0)return{};std::map<C,A> cells;for(Point p:points){if(!std::isfinite(p.x)||!std::isfinite(p.y)||!std::isfinite(p.z))continue;auto& a=cells[cell(v(p),size)];a.s=add(a.s,v(p));++a.n;}std::vector<Point> out;out.reserve(cells.size());for(auto& [_,a]:cells){V p=mul(a.s,1.0/a.n);out.push_back({(float)p.x,(float)p.y,(float)p.z});}return out;}
std::vector<PlaneDescriptor> extractPlanes(const std::vector<Point>& input,const PlaneExtractionOptions& requested){if(input.empty())return{};auto o=requested;V lo{1e300,1e300,1e300},hi{-1e300,-1e300,-1e300};for(Point p:input){lo.x=std::min(lo.x,(double)p.x);lo.y=std::min(lo.y,(double)p.y);lo.z=std::min(lo.z,(double)p.z);hi.x=std::max(hi.x,(double)p.x);hi.y=std::max(hi.y,(double)p.y);hi.z=std::max(hi.z,(double)p.z);}double span=std::max({hi.x-lo.x,hi.y-lo.y,hi.z-lo.z});if(!std::isfinite(span)||span<=0)return{};if(o.voxelSize<=0)o.voxelSize=std::max(span/100,1e-4);if(o.normalRadius<=0)o.normalRadius=o.voxelSize*3.5;if(o.maximumPlaneDistance<=0)o.maximumPlaneDistance=o.voxelSize*1.25;auto pts=voxelCentroids(input,o.voxelSize);auto smp=normals(pts,o.voxelSize,o.normalRadius,o.minimumNeighbours,o.minimumPlanarity);std::map<C,std::vector<std::size_t>> g;for(std::size_t i=0;i<pts.size();++i)g[cell(v(pts[i]),o.voxelSize)].push_back(i);std::vector<char> used(pts.size());std::vector<std::size_t> order(pts.size());std::iota(order.begin(),order.end(),0);std::stable_sort(order.begin(),order.end(),[&](auto a,auto b){return smp[a].planarity>smp[b].planarity;});std::vector<PlaneDescriptor> planes;double cosine=std::cos(o.maximumNormalAngleDegrees*3.141592653589793/180);
for(auto seed:order){if(o.cancellation&&o.cancellation->load())return{};if(used[seed]||!smp[seed].valid)continue;std::queue<std::size_t> q;std::vector<std::size_t> members;q.push(seed);used[seed]=1;V n=smp[seed].n,anchor=smp[seed].p;while(!q.empty()){auto i=q.front();q.pop();members.push_back(i);C c=cell(smp[i].p,o.voxelSize);for(int z=-1;z<=1;++z)for(int y=-1;y<=1;++y)for(int x=-1;x<=1;++x){auto it=g.find({c.x+x,c.y+y,c.z+z});if(it!=g.end())for(auto j:it->second){if(used[j]||!smp[j].valid)continue;if(std::abs(dot(n,smp[j].n))<cosine||std::abs(dot(n,sub(smp[j].p,anchor)))>o.maximumPlaneDistance)continue;used[j]=1;q.push(j);}}}if(members.size()<o.minimumSupport)continue;V center{};double quality=0;for(auto i:members){center=add(center,smp[i].p);quality+=smp[i].planarity;}center=mul(center,1.0/members.size());double cov[3][3]{},extent=0;for(auto i:members){V d=sub(smp[i].p,center);extent=std::max(extent,len(d));double e[3]{d.x,d.y,d.z};for(int r=0;r<3;++r)for(int k=0;k<3;++k)cov[r][k]+=e[r]*e[k];}auto e=eigenMin(cov);n={e[0],e[1],e[2]};if(!unit(n))continue;if(n.z<0||(n.z==0&&(n.y<0||(n.y==0&&n.x<0))))n=mul(n,-1);planes.push_back({{n.x,n.y,n.z},-dot(n,center),{center.x,center.y,center.z},members.size(),members.size()*o.voxelSize*o.voxelSize,extent,quality/members.size()});}
std::stable_sort(planes.begin(),planes.end(),[](auto&a,auto&b){return a.support>b.support;});if(planes.size()>o.maximumPlanes)planes.resize(o.maximumPlanes);return planes;}
}
