#include "tzf_pose_graph.h"
#include <algorithm>
#include <cmath>
#include <queue>
namespace tzf { namespace {
constexpr double pi=3.14159265358979323846;
double wrap(double a){return std::remainder(a,360.0);}
std::array<double,4> compose(const std::array<double,4>& a,const std::array<double,4>& b){double r=a[3]*pi/180,c=std::cos(r),s=std::sin(r);return{a[0]+c*b[0]-s*b[1],a[1]+s*b[0]+c*b[1],a[2]+b[2],wrap(a[3]+b[3])};}
std::array<double,4> inverse(const std::array<double,4>& a){double r=-a[3]*pi/180,c=std::cos(r),s=std::sin(r);return{-(c*a[0]-s*a[1]),-(s*a[0]+c*a[1]),-a[2],wrap(-a[3])};}
double residual(const std::array<double,4>& predicted,const std::array<double,4>& actual){double dx=predicted[0]-actual[0],dy=predicted[1]-actual[1],dz=predicted[2]-actual[2],da=wrap(predicted[3]-actual[3])*pi/180;return std::sqrt(dx*dx+dy*dy+dz*dz+da*da);}
double robust(double error,double scale){return error<=scale?1.0:scale/std::max(error,1e-12);}
}
PoseGraphResult optimizePoseGraph(std::size_t count,std::size_t fixed,const std::vector<std::array<double,4>>& initial,const std::vector<PoseGraphEdge>& edges,const PoseGraphOptions& o){PoseGraphResult out;if(count==0||fixed>=count){out.reason="invalid pose graph";return out;}out.poses=initial;if(out.poses.size()!=count)out.poses.assign(count,{});std::vector<std::vector<std::size_t>> adjacency(count);for(std::size_t k=0;k<edges.size();++k){const auto&e=edges[k];if(!e.enabled||e.reference>=count||e.moving>=count||e.reference==e.moving||!std::isfinite(e.weight)||e.weight<=0)continue;adjacency[e.reference].push_back(k);adjacency[e.moving].push_back(k);}std::vector<char> seen(count);std::queue<std::size_t> q;q.push(fixed);seen[fixed]=1;while(!q.empty()){auto n=q.front();q.pop();for(auto k:adjacency[n]){auto other=edges[k].reference==n?edges[k].moving:edges[k].reference;if(!seen[other]){seen[other]=1;q.push(other);}}}if(std::find(seen.begin(),seen.end(),0)!=seen.end()){out.reason="disconnected graph";return out;}
for(int iteration=0;iteration<o.maximumIterations;++iteration){if(o.cancellation&&o.cancellation->load()){out.reason="cancelled";return out;}double largestT=0,largestYaw=0;auto previous=out.poses;for(std::size_t node=0;node<count;++node){if(node==fixed)continue;double sx=0,sy=0,sz=0,sc=0,ss=0,total=0;for(auto k:adjacency[node]){const auto&e=edges[k];std::array<double,4> proposal;if(e.moving==node)proposal=compose(previous[e.reference],e.relative);else proposal=compose(previous[e.moving],inverse(e.relative));double err=residual(proposal,previous[node]);double w=e.weight*robust(err,o.robustTranslationScale);sx+=w*proposal[0];sy+=w*proposal[1];sz+=w*proposal[2];sc+=w*std::cos(proposal[3]*pi/180);ss+=w*std::sin(proposal[3]*pi/180);total+=w;}if(total<=0)continue;std::array<double,4> next{sx/total,sy/total,sz/total,std::atan2(ss,sc)*180/pi};double dx=next[0]-previous[node][0],dy=next[1]-previous[node][1],dz=next[2]-previous[node][2];largestT=std::max(largestT,std::sqrt(dx*dx+dy*dy+dz*dz));largestYaw=std::max(largestYaw,std::abs(wrap(next[3]-previous[node][3])));out.poses[node]=next;}++out.iterations;if(largestT<o.translationTolerance&&largestYaw<o.yawToleranceDegrees)break;}
out.edgeResiduals.reserve(edges.size());double residualSum=0,largestResidual=0;std::size_t residualCount=0;for(const auto&e:edges){if(!e.enabled||e.reference>=count||e.moving>=count){out.edgeResiduals.push_back(0);continue;}const double value=residual(compose(out.poses[e.reference],e.relative),out.poses[e.moving]);if(!std::isfinite(value)){out.reason="non-finite graph residual";out.poses=initial;return out;}out.edgeResiduals.push_back(value);residualSum+=value;largestResidual=std::max(largestResidual,value);++residualCount;}const double meanResidual=residualCount==0?0:residualSum/residualCount;if(largestResidual>o.maximumEdgeResidual||meanResidual>o.maximumMeanEdgeResidual){out.reason="inconsistent pose graph";out.poses=initial;return out;}out.accepted=true;out.reason="accepted";return out;}
}
